/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/harvest/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a Google SERP search, or a full People-Also-Ask harvest
         * @description Set `serpOnly: true` for a pure organic-results/SERP call (~0.1 credit). Omit or
         *     set `false` for a full People-Also-Ask harvest, which also returns SERP data
         *     (~1 credit base + 0.2 credit per question actually returned; unused estimate is
         *     refunded). Runs synchronously and returns the result inline.
         */
        post: operations["harvestSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your harvest jobs (most recent first) */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one harvest job by id, including its result and attempt log */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent SERP/harvest activity (jobs and one-off request events combined) */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent credit ledger entries (debits, credits, refunds) */
        get: operations["getLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract a single page (markdown/HTML, headings, optional screenshot/branding/media)
         * @description Costs 0.1 credit per page.
         */
        post: operations["extractUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spider a site and return its discovered URL inventory
         * @description Flat 0.5 credit per call, regardless of URL count discovered.
         */
        post: operations["mapSiteUrls"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract-site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crawl and extract every page of a site (also serves audit_site)
         * @description 0.1 credit per page crawled (estimated up front against `maxPages`, then
         *     reconciled to the actual page count crawled; unused estimate refunded). Set
         *     `background: true` to enqueue an async crawl and poll
         *     `GET /extract-site/status/{id}` instead of waiting inline — recommended above a
         *     few hundred pages.
         */
        post: operations["extractSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract-site/status/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a background extract-site job */
        get: operations["getExtractSiteStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/youtube/harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search YouTube, or list a channel's videos
         * @description Costs 0.2 credit per call.
         */
        post: operations["youtubeHarvest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/youtube/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe a YouTube video's captions
         * @description 0.2 credit per minute; a 5-minute hold is taken up front and reconciled to actual duration.
         */
        post: operations["youtubeTranscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture a full-page PNG screenshot of a URL
         * @description Costs 0.1 credit. Returns the raw PNG bytes, not JSON.
         */
        post: operations["screenshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/ad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract one Facebook Ad Library ad (all its variants) by URL or library ID
         * @description Costs 0.2 credit.
         */
        post: operations["facebookAd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/page-intel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List an advertiser's active/recent ads by page ID, library ID, or search query
         * @description Costs 0.2 credit.
         */
        post: operations["facebookPageIntel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe a Facebook ad's video by direct video URL
         * @description 0.2 credit per minute; a 5-minute hold is taken and reconciled to actual duration.
         */
        post: operations["facebookAdTranscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/video-transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe an organic Facebook video, reel, or share URL (not an ad)
         * @description 0.2 credit per minute; a 5-minute hold is taken and reconciled to actual duration.
         */
        post: operations["facebookVideoTranscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search the Facebook Ad Library by keyword and return matching advertisers
         * @description Costs 0.6 credit.
         */
        post: operations["facebookSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facebook/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy-download a Facebook/Instagram CDN media URL (fbcdn.net / cdninstagram.com only)
         * @description Free — no credit cost. Streams the raw file bytes.
         */
        post: operations["facebookMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google-ads/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find advertisers in the Google Ads Transparency Center by keyword
         * @description Costs 0.6 credit.
         */
        post: operations["googleAdsSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google-ads/page-intel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List one advertiser's creatives by advertiser ID or domain
         * @description Costs 0.2 credit.
         */
        post: operations["googleAdsPageIntel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google-ads/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe a Google ad's video by direct video URL
         * @description 0.2 credit per minute; a 5-minute hold is taken and reconciled to actual duration.
         */
        post: operations["googleAdsTranscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instagram/profile-content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List a public Instagram profile's grid content
         * @description Costs 0.4 credit per profile scan. Provide `handle` or `url`.
         */
        post: operations["instagramProfileContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instagram/media-download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract and optionally download media from an Instagram post, reel, or tv URL
         * @description Costs 0.4 credit; +0.05 credit if `includeTranscript` is used.
         */
        post: operations["instagramMediaDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reddit/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture a Reddit post and its comment tree
         * @description Costs 2 credits. Refunded automatically if Reddit blocks the request after retries.
         */
        post: operations["redditThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a frame-by-frame video breakdown (async — poll /video/status)
         * @description Full multi-lens breakdown: samples frames across a video (up to 30 minutes),
         *     analyzes each with vision AI, transcribes audio, then produces summary,
         *     pacing/energy, words-per-minute, topic outline, key points, hook analysis,
         *     visual style, and a how-to-replicate recipe. ~0.667 credit per 120 frames
         *     requested (max 480 frames); billed down automatically if the video can't use
         *     the requested frames, refunded fully if the run fails.
         */
        post: operations["videoAnalyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll a video breakdown run */
        post: operations["videoAnalyzeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Google Maps for businesses matching a query and location
         * @description Costs 0.5 credit. Returns up to 50 business/profile candidates.
         */
        post: operations["mapsSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deep-dive one Google Maps business by name and location, with reviews
         * @description 3 credits base; +0.1 credit per review card when `includeReviews` is true.
         */
        post: operations["mapsPlaceIntel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directory/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Google Maps business search across many cities in a state/region at once
         * @description Cost is `0.5 credit × number of markets resolved` for the query — see `GET /workflows/definitions` for related workflow shapes. Failed cities are refunded individually.
         */
        post: operations["directoryWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/serp-intelligence/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structured SERP capture with AI Overview/AI Mode detection, entity IDs, and location-match evidence
         * @description Costs 0.1 credit. Rate-limited to 60 requests/minute per account.
         */
        post: operations["serpIntelligenceCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/serp-intelligence/page-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and archive full-content snapshots (HTML/text/markdown/screenshot) of specific URLs
         * @description Costs 0.1 credit per URL (max 25 per call). Rate-limited to 60 requests/minute per account.
         */
        post: operations["serpIntelligencePageSnapshots"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available workflow definitions and their input schemas */
        get: operations["listWorkflowDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a workflow run (some workflows execute stepwise; check `done` in the response) */
        post: operations["runWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance a stepwise workflow run by one step */
        post: operations["advanceWorkflowRunStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your workflow runs */
        get: operations["listWorkflowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one workflow run, including its artifacts */
        get: operations["getWorkflowRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/runs/{id}/artifacts/{artifactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download one artifact produced by a workflow run */
        get: operations["getWorkflowRunArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your workflow schedules */
        get: operations["listWorkflowSchedules"];
        put?: never;
        /** Create a recurring schedule for a workflow */
        post: operations["createWorkflowSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a workflow schedule */
        delete: operations["deleteWorkflowSchedule"];
        options?: never;
        head?: never;
        /** Update a workflow schedule */
        patch: operations["patchWorkflowSchedule"];
        trace?: never;
    };
    "/workflows/schedules/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a workflow schedule immediately, out of cadence */
        post: operations["runWorkflowScheduleNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            error_code?: string;
            message?: string;
        };
        /** @description Shared structured error shape used by SERP Intelligence endpoints. */
        StructuredError: {
            error_code: string;
            error_type: string;
            message: string;
            retryable: boolean;
            attempts?: {
                [key: string]: unknown;
            }[];
        };
        InsufficientBalanceError: {
            /** @enum {string} */
            error: "insufficient_balance";
            /** @enum {string} */
            error_code: "insufficient_balance";
            message: string;
            balance_credits: number;
            required_credits: number;
            /** Format: uri */
            topup_url: string;
        };
        ConcurrencyLimitError: {
            error?: string;
            message: string;
            /** @enum {string} */
            error_code: "concurrency_limit_exceeded";
            /** @enum {string} */
            error_type?: "concurrency_limit";
            retryable?: boolean;
            active: number;
            limit: number;
            operation: string;
            /** Format: uri */
            upgrade_url?: string;
            /** @description CLI command to buy an extra concurrency slot. */
            upgrade_command?: string;
        };
        HarvestSyncRequest: {
            /** @description Search query. */
            query: string;
            /** @description e.g. "Austin, TX". */
            location?: string;
            /**
             * @description PAA drill-down depth. Ignored when serpOnly is true.
             * @default 4
             */
            depth: number;
            /**
             * @description Max PAA questions to harvest. Ignored when serpOnly is true.
             * @default 30
             */
            maxQuestions: number;
            /**
             * @description Google country code.
             * @default us
             */
            gl: string;
            /**
             * @description Google language code.
             * @default en
             */
            hl: string;
            /**
             * @default desktop
             * @enum {string}
             */
            device: "desktop" | "mobile";
            /**
             * @default none
             * @enum {string}
             */
            proxyMode: "location" | "configured" | "none";
            /** @description US ZIP to localize the proxy egress to. */
            proxyZip?: string;
            /**
             * @description Organic result pages to fetch.
             * @default 1
             */
            pages: number;
            /**
             * @description true = pure SERP call (search_serp); false = full PAA harvest.
             * @default false
             */
            serpOnly: boolean;
            /** @default false */
            debug: boolean;
        };
        HarvestSyncResponse: {
            job_id: string;
            /** @enum {string} */
            status: "done" | "cancelled" | "failed";
            /** @description Present when status is done — SERP/PAA harvest result. */
            result?: {
                [key: string]: unknown;
            };
            attempts?: {
                [key: string]: unknown;
            }[];
            error?: string;
        };
        JobRecord: {
            id?: string;
            status?: string;
            query?: string;
            result?: {
                [key: string]: unknown;
            } | null;
            attempts?: {
                [key: string]: unknown;
            }[];
            created_at?: string;
        };
        ExtractUrlRequest: {
            /** Format: uri */
            url: string;
            /** @default false */
            screenshot: boolean;
            /**
             * @default desktop
             * @enum {string}
             */
            screenshotDevice: "desktop" | "mobile";
            /**
             * @description Extract brand colors/fonts/logo.
             * @default false
             */
            extractBranding: boolean;
            /** @default false */
            downloadMedia: boolean;
            mediaTypes?: ("image" | "video" | "audio")[];
            /** @default false */
            allowLocal: boolean;
            /**
             * @description Save the extracted content into an mcp-memory vault.
             * @default false
             */
            depositToVault: boolean;
            vaultName?: string;
        };
        /** @description Spreads the page extraction result plus optional screenshot/branding/media/memory. */
        ExtractUrlResponse: {
            title?: string | null;
            bodyMarkdown?: string;
            bodyHtml?: string;
            headings?: {
                [key: string]: unknown;
            }[];
            screenshot?: {
                base64?: string;
                sizeBytes?: number;
                device?: string;
            } | null;
            branding?: {
                [key: string]: unknown;
            } | null;
            media?: {
                [key: string]: unknown;
            } | null;
            /** @description Present when depositToVault was true. */
            memory?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        MapUrlsRequest: {
            /** Format: uri */
            url: string;
            /** @default 500 */
            maxUrls: number;
            /** @default 12 */
            concurrency: number;
            /**
             * @description Use a real browser session for JS-heavy sites.
             * @default false
             */
            browserFallback: boolean;
            /** @default false */
            kernelFallback: boolean;
        };
        MapUrlsResponse: {
            urls?: string[];
        } & {
            [key: string]: unknown;
        };
        ExtractSiteRequest: {
            /** Format: uri */
            url: string;
            /** @default 100 */
            maxPages: number;
            /**
             * @description Enqueue an async crawl instead of waiting inline.
             * @default false
             */
            background: boolean;
            /** @default false */
            rotateProxies: boolean;
            /** @default 30 */
            rotateProxyEvery: number;
            /** @default false */
            browserFallback: boolean;
            /** @default false */
            kernelFallback: boolean;
            formats?: ("markdown" | "links" | "json" | "images" | "branding")[];
        };
        /** @description Full synchronous crawl result. */
        ExtractSiteResponse: {
            pages?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        ExtractSiteQueuedResponse: {
            jobId: string;
            /** @enum {string} */
            status: "pending";
            statusUrl: string;
        };
        ExtractSiteStatus: {
            jobId?: string;
            status?: string;
            startUrl?: string;
            totalUrls?: number;
            doneUrls?: number;
            artifacts?: {
                [key: string]: unknown;
            }[];
            error?: string | null;
            updatedAt?: string;
        };
        YoutubeHarvestRequest: {
            /** @enum {string} */
            mode: "search" | "channel";
            /** @description Required when mode is search. */
            query?: string;
            /** @description Required when mode is channel — @handle or UC... channel ID. */
            channelHandle?: string;
            /** @default 50 */
            maxVideos: number;
        };
        TranscriptResponse: {
            videoId?: string;
            text?: string;
            chunks?: {
                timestamp?: number[];
                text?: string;
            }[];
            durationMs?: number;
            markdown?: string;
            html?: string;
        };
        MapsSearchRequest: {
            query: string;
            location?: string;
            /** @default us */
            gl: string;
            /** @default en */
            hl: string;
            /** @default 10 */
            maxResults: number;
            /**
             * @default location
             * @enum {string}
             */
            proxyMode: "location" | "configured" | "none";
            proxyZip?: string;
            /** @default false */
            debug: boolean;
        };
        MapsPlaceRequest: {
            businessName: string;
            location: string;
            /** @default us */
            gl: string;
            /** @default en */
            hl: string;
            /** @default false */
            includeReviews: boolean;
            /** @default 50 */
            maxReviews: number;
        };
        SerpIntelligenceCaptureRequest: {
            query: string;
            location?: string;
            /** @default us */
            gl: string;
            /** @default en */
            hl: string;
            /**
             * @default desktop
             * @enum {string}
             */
            device: "desktop" | "mobile";
            /**
             * @default none
             * @enum {string}
             */
            proxyMode: "location" | "configured" | "none";
            proxyZip?: string;
            /** @default 1 */
            pages: number;
            /** @default false */
            debug: boolean;
            /** @default false */
            includePageSnapshots: boolean;
            /** @default 0 */
            pageSnapshotLimit: number;
        };
        SerpIntelligencePageSnapshotsRequest: {
            urls: string[];
            targets?: {
                /** Format: uri */
                url?: string;
                /**
                 * @default configured_target
                 * @enum {string}
                 */
                sourceKind: "organic" | "ai_citation" | "local_pack_website" | "configured_target" | "site_subject";
                sourcePosition?: number;
            }[];
            /** @default 2 */
            maxConcurrency: number;
            /** @default 15000 */
            timeoutMs: number;
            /** @default false */
            debug: boolean;
        };
        SerpIntelligenceOrganicResult: {
            position?: number;
            title?: string;
            url?: string;
            domain?: string;
            cite?: string | null;
            snippet?: string | null;
            isRedditStyle?: boolean;
            inlineRating?: {
                value?: string;
                count?: string;
            } | null;
        };
        SerpIntelligenceHarvestResult: {
            seed?: string;
            location?: string | null;
            extractedAt?: string;
            totalQuestions?: number;
            /** @enum {string} */
            surface?: "web" | "aim" | "unknown";
            aiOverview?: {
                detected?: boolean;
                text?: string | null;
                citations?: {
                    text?: string;
                    href?: string;
                }[];
            };
            aiMode?: {
                detected?: boolean;
                text?: string | null;
                citations?: {
                    text?: string;
                    href?: string;
                }[];
            };
            tree?: unknown[];
            flat?: unknown[];
            videos?: unknown[];
            forums?: unknown[];
            organicResults?: components["schemas"]["SerpIntelligenceOrganicResult"][];
            localPack?: unknown[];
            entityIds?: {
                entities?: {
                    name?: string;
                    kgId?: string | null;
                    cid?: string | null;
                    gcid?: string | null;
                }[];
                kgIds?: string[];
                cids?: string[];
                gcids?: string[];
            };
            stats?: {
                seed?: string;
                totalQuestions?: number;
                maxDepthReached?: number;
                durationMs?: number;
                errorCount?: number;
            };
            diagnostics?: {
                [key: string]: unknown;
            };
            whatPeopleSaying?: unknown[];
        };
        SerpPageSnapshotCapture: {
            url?: string;
            requestedUrl?: string;
            finalUrl?: string | null;
            /** @enum {string} */
            sourceKind?: "organic" | "ai_citation" | "local_pack_website" | "configured_target" | "site_subject";
            sourcePosition?: number | null;
            /** @enum {string} */
            status?: "captured" | "skipped" | "failed";
            /** @enum {string|null} */
            fetchedVia?: "fetch" | "headless" | "browser" | "mcp" | null;
            httpStatus?: number | null;
            contentType?: string | null;
            title?: string | null;
            canonicalUrl?: string | null;
            metaDescription?: string | null;
            headings?: {
                level?: number;
                text?: string;
            }[];
            artifact?: {
                htmlBlobUrl?: string | null;
                textBlobUrl?: string | null;
                markdownBlobUrl?: string | null;
                screenshotBlobUrl?: string | null;
                contentSha256?: string | null;
                capturedAt?: string | null;
            };
            error?: {
                code?: string;
                message?: string;
            } | null;
        };
        SerpIntelligenceCaptureAttempt: {
            attemptNumber?: number;
            outcome?: string;
            startedAt?: string;
            completedAt?: string;
            durationMs?: number;
            problemCode?: string;
            message?: string;
            kernelSessionId?: string | null;
            cleanupSucceeded?: boolean | null;
        };
        SerpIntelligenceCaptureResponse: {
            harvestResult?: components["schemas"]["SerpIntelligenceHarvestResult"];
            attempts?: components["schemas"]["SerpIntelligenceCaptureAttempt"][];
            locationEvidence?: {
                [key: string]: unknown;
            } | null;
            pageSnapshotArtifacts?: components["schemas"]["SerpPageSnapshotCapture"][];
            billing?: {
                creditsUsed?: number;
                requestId?: string;
                jobId?: string;
            };
        };
        SerpIntelligencePageSnapshotsResponse: {
            pageSnapshotArtifacts?: components["schemas"]["SerpPageSnapshotCapture"][];
            attempts?: components["schemas"]["SerpIntelligenceCaptureAttempt"][];
        };
        WorkflowRun: {
            id?: string;
            workflow_id?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
            input?: {
                [key: string]: unknown;
            };
            step_index?: number;
            created_at?: string;
            completed_at?: string | null;
            error_message?: string | null;
            artifacts?: {
                id?: string;
                kind?: string;
                label?: string;
                downloadUrl?: string;
            }[];
        } & {
            [key: string]: unknown;
        };
        WorkflowRunStepResponse: {
            run?: components["schemas"]["WorkflowRun"];
            /** @description Present once the run reaches a terminal state. */
            summary?: {
                [key: string]: unknown;
            } | null;
            step?: {
                index?: number;
                id?: string;
                title?: string;
                totalSteps?: number;
                output?: {
                    [key: string]: unknown;
                };
                warnings?: string[];
            } | null;
            nextStep?: {
                index?: number;
                id?: string | null;
                title?: string | null;
            } | null;
            done?: boolean;
        };
        WorkflowSchedule: {
            id?: string;
            workflow_id?: string;
            name?: string;
            /** @enum {string} */
            status?: "active" | "paused";
            input?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            cadence?: "daily" | "weekly" | "monthly";
            timezone?: string;
            webhook_url?: string | null;
            next_run_at?: string | null;
        };
    };
    responses: {
        /** @description Missing or invalid `x-api-key`. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request body. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not enough credit balance to cover this call's cost. */
        InsufficientBalance: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InsufficientBalanceError"];
            };
        };
        /** @description Too many concurrent operations for your account's concurrency limit. */
        ConcurrencyLimitExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConcurrencyLimitError"];
            };
        };
        /** @description Invalid request body. */
        StructuredBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StructuredError"];
            };
        };
        /** @description Too many SERP Intelligence requests (60/minute limit). */
        StructuredRateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StructuredError"];
            };
        };
        /** @description Capture failed. */
        StructuredCaptureFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StructuredError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    harvestSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HarvestSyncRequest"];
            };
        };
        responses: {
            /** @description Harvest completed (or failed/cancelled — check `status`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestSyncResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 most recent rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 most recent ledger rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    extractUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractUrlRequest"];
            };
        };
        responses: {
            /** @description Extraction result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    mapSiteUrls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapUrlsRequest"];
            };
        };
        responses: {
            /** @description URL inventory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapUrlsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    extractSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractSiteRequest"];
            };
        };
        responses: {
            /** @description Full crawl result (synchronous mode) or a queued job (`background:true`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractSiteResponse"] | components["schemas"]["ExtractSiteQueuedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Failed to enqueue the background crawl. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getExtractSiteStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractSiteStatus"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    youtubeHarvest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YoutubeHarvestRequest"];
            };
        };
        responses: {
            /** @description Video list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description YouTube blocked the request (CAPTCHA) — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    youtubeTranscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description YouTube video ID (not a full URL). */
                    videoId: string;
                };
            };
        };
        responses: {
            /** @description Transcript with plain text, timestamped chunks, markdown, and HTML renderings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    screenshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    /**
                     * @default desktop
                     * @enum {string}
                     */
                    device?: "desktop" | "mobile";
                    /**
                     * @description Allow non-public/local URLs. Off by default.
                     * @default false
                     */
                    allowLocal?: boolean;
                };
            };
        };
        responses: {
            /** @description PNG image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            /** @description Screenshot capture failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facebookAd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A facebook.com/ads/library ad URL. */
                    url?: string;
                    libraryId?: string;
                    /** @default true */
                    openModal?: boolean;
                };
            };
        };
        responses: {
            /** @description Ad detail with creative variants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Facebook blocked the request (CAPTCHA/soft-block) — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facebookPageIntel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pageId?: string;
                    query?: string;
                    libraryId?: string;
                    /** @default 50 */
                    maxAds?: number;
                    /**
                     * @description ISO 3166-1 alpha-2, e.g. US.
                     * @default US
                     */
                    country?: string;
                };
            };
        };
        responses: {
            /** @description Ads for the advertiser. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Soft-blocked with an empty result — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facebookAdTranscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    videoUrl: string;
                };
            };
        };
        responses: {
            /** @description Transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    facebookVideoTranscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description facebook.com or fb.watch URL. */
                    url: string;
                    /**
                     * @default best
                     * @enum {string}
                     */
                    quality?: "best" | "hd" | "sd";
                };
            };
        };
        responses: {
            /** @description Video metadata plus transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    facebookSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    /** @default US */
                    country?: string;
                    /** @default 10 */
                    maxResults?: number;
                };
            };
        };
        responses: {
            /** @description Matching advertisers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        query?: string;
                        searchUrl?: string;
                        results?: {
                            name?: string;
                            pageName?: string;
                            pageId?: string | null;
                            libraryId?: string;
                            sampleLibraryId?: string;
                            adCount?: number;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Soft-blocked with an empty result — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    facebookMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    filename?: string;
                };
            };
        };
        responses: {
            /** @description Media bytes with the original content type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The CDN fetch failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleAdsSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    /**
                     * @description ISO 3166-1 alpha-2.
                     * @default US
                     */
                    region?: string;
                    /** @default 10 */
                    maxResults?: number;
                };
            };
        };
        responses: {
            /** @description Matching advertisers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description No advertisers found, or blocked — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleAdsPageIntel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    advertiserId?: string;
                    domain?: string;
                    /** @default US */
                    region?: string;
                    /** @default 50 */
                    maxAds?: number;
                };
            };
        };
        responses: {
            /** @description Advertiser creatives. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description No ads found, or blocked — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleAdsTranscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    videoUrl: string;
                };
            };
        };
        responses: {
            /** @description Transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    instagramProfileContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    handle?: string;
                    url?: string;
                    /** @default 50 */
                    maxItems?: number;
                    /** @default 10 */
                    maxScrolls?: number;
                    /** @default 1200 */
                    scrollDelayMs?: number;
                    /** @default 4 */
                    stableScrollLimit?: number;
                };
            };
        };
        responses: {
            /** @description Profile content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Blocked/CAPTCHA. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instagramMediaDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Instagram post/reel/tv URL. */
                    url: string;
                    /**
                     * @default [
                     *       "image",
                     *       "video",
                     *       "audio"
                     *     ]
                     */
                    mediaTypes?: ("image" | "video" | "audio")[];
                    /** @default true */
                    downloadMedia?: boolean;
                    /** @default false */
                    downloadAllTracks?: boolean;
                    /** @default false */
                    includeTranscript?: boolean;
                    /**
                     * @description Mux separately-downloaded video+audio tracks into one file with ffmpeg.
                     * @default true
                     */
                    mux?: boolean;
                };
            };
        };
        responses: {
            /** @description Extraction result with download manifest and optional transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Blocked/CAPTCHA. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redditThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A reddit.com or redd.it thread URL. */
                    url: string;
                    maxComments?: number;
                };
            };
        };
        responses: {
            /** @description Thread with comments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title?: string;
                        author?: string | null;
                        score?: string | null;
                        postBody?: string;
                        numComments?: number;
                        comments?: {
                            author?: string | null;
                            score?: string;
                            depth?: number;
                            body?: string;
                        }[];
                        sourceUrl?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description Reddit blocked the request after retries — billed amount was refunded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    videoAnalyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description Direct video file URL.
                     */
                    sourceUrl: string;
                    /** @default 2 */
                    intervalS?: number;
                    /** @default 120 */
                    maxFrames?: number;
                    /**
                     * @default standard
                     * @enum {string}
                     */
                    detail?: "fast" | "standard" | "deep";
                    /**
                     * @description Destination memory vault name.
                     * @default Library
                     */
                    vault?: string;
                };
            };
        };
        responses: {
            /** @description Run queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        runId?: string;
                        /** @enum {string} */
                        status?: "queued";
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            /** @description Memory backend unavailable, or the run failed to start (billed amount refunded). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    videoAnalyzeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    runId: string;
                };
            };
        };
        responses: {
            /** @description Run status. `artifactPath`/`report` are present once `status` is `done`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        runId?: string;
                        /** @description e.g. queued, running, done, failed. */
                        status?: string;
                        progress?: {
                            analyzed?: number;
                            total?: number;
                        } | null;
                        frameCount?: number | null;
                        artifactPath?: string;
                        /** @description Markdown report. */
                        report?: string;
                        error?: string;
                        reconciliation?: {
                            billedMc?: number;
                            refundedMc?: number;
                            effectiveFrames?: number | null;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory backend unavailable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mapsSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapsSearchRequest"];
            };
        };
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description CAPTCHA/blocked — retryable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mapsPlaceIntel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapsPlaceRequest"];
            };
        };
        responses: {
            /** @description Place detail with optional reviews. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
            /** @description CAPTCHA/blocked — retryable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    directoryWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Business category to search, e.g. "roofers". */
                    query: string;
                    /** @description US state code or name. */
                    state: string;
                    /** @description Minimum city population to include as a market. */
                    minPop?: number;
                    /** @description Max results per city. */
                    perCity?: number;
                };
            };
        };
        responses: {
            /** @description Per-city results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        query?: string;
                        state?: string;
                        totalResultCount?: number;
                        cities?: {
                            city?: string;
                            /** @enum {string} */
                            status?: "done" | "failed";
                            results?: {
                                [key: string]: unknown;
                            }[];
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            /** @description Directory workflow failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    serpIntelligenceCapture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerpIntelligenceCaptureRequest"];
            };
        };
        responses: {
            /** @description Structured SERP capture. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpIntelligenceCaptureResponse"];
                };
            };
            400: components["responses"]["StructuredBadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["StructuredRateLimited"];
            500: components["responses"]["StructuredCaptureFailed"];
        };
    };
    serpIntelligencePageSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerpIntelligencePageSnapshotsRequest"];
            };
        };
        responses: {
            /** @description Page snapshot artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpIntelligencePageSnapshotsResponse"];
                };
            };
            400: components["responses"]["StructuredBadRequest"];
            402: components["responses"]["InsufficientBalance"];
            429: components["responses"]["StructuredRateLimited"];
            500: components["responses"]["StructuredCaptureFailed"];
        };
    };
    listWorkflowDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflows?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    runWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    workflowId: string;
                    /** @description Validated against the workflow's own input schema — see GET /workflows/definitions. */
                    input?: {
                        [key: string]: unknown;
                    };
                    /**
                     * Format: uri
                     * @description HTTPS URL to receive a signed webhook on completion.
                     */
                    webhookUrl?: string;
                };
            };
        };
        responses: {
            /** @description Run started — either completed inline or advanced one step (`done: false` means call POST /workflows/runs/{id}/step to continue). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunStepResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    advanceWorkflowRunStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Step result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunStepResponse"];
                };
            };
            /** @description This workflow doesn't support stepwise execution. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The run is already in a terminal state, or has no remaining steps. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
    listWorkflowRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs?: components["schemas"]["WorkflowRun"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWorkflowRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run?: components["schemas"]["WorkflowRun"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getWorkflowRunArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                artifactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact file bytes, with the artifact's own content type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The artifact file is no longer available. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkflowSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schedules?: components["schemas"]["WorkflowSchedule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWorkflowSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    workflowId: string;
                    name?: string;
                    input?: {
                        [key: string]: unknown;
                    };
                    /**
                     * @default weekly
                     * @enum {string}
                     */
                    cadence?: "daily" | "weekly" | "monthly";
                    /** @default UTC */
                    timezone?: string;
                    /** Format: uri */
                    webhookUrl?: string;
                    /** Format: date-time */
                    nextRunAt?: string;
                };
            };
        };
        responses: {
            /** @description Schedule created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schedule?: components["schemas"]["WorkflowSchedule"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteWorkflowSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchWorkflowSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    status?: "active" | "paused";
                    input?: {
                        [key: string]: unknown;
                    };
                    /** @enum {string} */
                    cadence?: "daily" | "weekly" | "monthly";
                    timezone?: string;
                    /** Format: uri */
                    webhookUrl?: string | null;
                    /** Format: date-time */
                    nextRunAt?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schedule?: components["schemas"]["WorkflowSchedule"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    runWorkflowScheduleNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run?: components["schemas"]["WorkflowRun"];
                        summary?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["ConcurrencyLimitExceeded"];
            500: components["responses"]["ServerError"];
        };
    };
}
