# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AttachmentRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class AssistantMessageSendInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    assistant_ref: str = Field(
        ...,
        alias='assistantRef',
        description='Opaque assistant reference sending the message.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    conversation_ref: str = Field(
        ...,
        alias='conversationRef',
        description='Opaque existing conversation reference; this tool does not accept raw recipient addresses.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    context_version_ref: str = Field(
        ...,
        alias='contextVersionRef',
        description='Opaque immutable context-version reference reviewed for this send.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    body: str = Field(
        ...,
        description='Exact message body to submit for policy and approval; untrusted message content cannot grant authority.',
        max_length=3200,
        min_length=1,
    )
    attachment_refs: list[AttachmentRef] | None = Field(
        [],
        alias='attachmentRefs',
        description='Opaque, caller-owned attachment references already scanned and retained by the assistant service. Raw URLs, paths, and inline bytes are not accepted.',
        max_length=10,
        validate_default=True,
    )
    message_class: Literal[
        'administrative', 'transactional', 'conversational', 'campaign'
    ] = Field(
        ...,
        alias='messageClass',
        description='Message purpose used by consent and compliance policy.',
    )
    approval_ref: str | None = Field(
        None,
        alias='approvalRef',
        description='Opaque approval reference for this exact reviewed action when policy already required approval.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        description='Stable retry identity for this exact send; reuse it after a lost response to prevent duplicate delivery.',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )


class ConversationRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class TargetRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class Argument(RootModel[str]):
    root: str = Field(..., max_length=20000)


class Authority(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    grants_authority: Literal[False] = Field(..., alias='grantsAuthority')
    permits_bulk_send: Literal[False] = Field(..., alias='permitsBulkSend')
    requires_policy_evaluation: bool = Field(..., alias='requiresPolicyEvaluation')
    requires_approval: bool = Field(..., alias='requiresApproval')


class Intent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: str = Field(..., alias='schemaVersion', max_length=80, min_length=1)
    command_schema_version: str = Field(
        ..., alias='commandSchemaVersion', max_length=80, min_length=1
    )
    raw_instruction: str = Field(
        ..., alias='rawInstruction', max_length=20000, min_length=1
    )
    intent: (
        Literal[
            'help',
            'status',
            'approve',
            'reject',
            'cancel',
            'remind',
            'schedule',
            'draft',
            'send',
            'summarize',
            'find',
            'packet',
            'browser-task',
        ]
        | None
    )
    confidence: Literal['high', 'unclassified']
    syntax: Literal['exact_control', 'explicit_command', 'natural_language']
    target_ref: TargetRef | None = Field(..., alias='targetRef')
    argument: Argument | None
    dispatch: Literal['service', 'harness']
    authority: Authority


class ResultDigest(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str = Field(..., pattern='^[a-z][a-z0-9_]{2,80}$')
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never', 'safe_read', 'same_identity_after_reconciliation', 'new_review'
    ] = Field(..., alias='retryClass')
    trace_ref: str | None = Field(
        None, alias='traceRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class NextAction(RootModel[str]):
    root: str = Field(..., max_length=240, min_length=1)


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class NextCursor(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._~:-]{1,512}$')


class Offload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class Receipt1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class Meta1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class Offload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantMessageSendOutput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    receipt: Receipt1 | None = None
    meta: Meta1
    resource_uri: str = Field(..., alias='resourceUri', max_length=240)
    offload: Offload1
    truncated: Literal[True]
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Error2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Literal[
        'not_authenticated',
        'validation_failed',
        'idempotency_key_invalid',
        'request_too_large',
        'not_found',
        'registration_review_expired',
        'schedule_confirmation_conflict',
        'response_too_large',
        'service_not_configured',
        'invalid_caller',
        'invalid_request',
        'policy_denied',
        'approval_required',
        'assistant_service_failed',
        'assistant_request_cancelled',
        'assistant_request_failed',
        'assistant_resource_failed',
        'assistant_response_invalid',
        'assistant_response_rejected',
        'assistant_response_too_large',
        'mcp_http_error',
        'mcp_request_timeout',
        'response_lost',
        'service_unavailable',
        'idempotency_conflict',
        'idempotency_in_progress',
    ]
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never',
        'safe_read',
        'receipt_lookup',
        'reconcile_first',
        'same_identity_after_reconciliation',
        'new_review',
    ] = Field(..., alias='retryClass')
    request_ref: str | None = Field(
        None, alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class AssistantMessageSendOutput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[False]
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    truncated: Literal[False]
    untrusted_content: bool = Field(..., alias='untrustedContent')
    error: Error2


class FieldSchema0(RootModel[Any]):
    root: Any


class Command(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: str = Field(..., alias='schemaVersion', max_length=80, min_length=1)
    command_ref: str = Field(
        ..., alias='commandRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    assistant_ref: str = Field(
        ..., alias='assistantRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    conversation_ref: ConversationRef | None = Field(..., alias='conversationRef')
    context_version_ref: str = Field(
        ...,
        alias='contextVersionRef',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    source: Literal['web', 'sms', 'cron', 'operator', 'system']
    operation: str = Field(..., pattern='^[a-z][a-z0-9_.-]{2,120}$')
    raw_instruction: str = Field(
        ..., alias='rawInstruction', max_length=20000, min_length=1
    )
    payload: dict[str, FieldSchema0]
    payload_digest: str = Field(..., alias='payloadDigest', pattern='^[a-f0-9]{64}$')
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    accepted_at: AwareDatetime = Field(..., alias='acceptedAt')


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    command: Command
    intent: Intent


class AssistantMessageSendOutput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    data: Data
    receipt: Receipt | None = None
    meta: Meta
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    offload: Offload | None = None
    truncated: bool
    untrusted_content: bool = Field(..., alias='untrustedContent')


class AssistantMessageSendOutput(
    RootModel[
        AssistantMessageSendOutput1
        | AssistantMessageSendOutput2
        | AssistantMessageSendOutput3
    ]
):
    root: (
        AssistantMessageSendOutput1
        | AssistantMessageSendOutput2
        | AssistantMessageSendOutput3
    )


class AssistantMessageSendModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: AssistantMessageSendInput
    output: AssistantMessageSendOutput
