# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AssistantNumberStatusInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    number_ref: str = Field(
        ...,
        alias='numberRef',
        description='Opaque caller-owned number reference whose readiness should be read.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )


class Registration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    registration_ref: str = Field(
        ...,
        alias='registrationRef',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    state: Literal[
        'unavailable',
        'draft',
        'ready_for_review',
        'submitted',
        'pending',
        'approved',
        'rejected',
        'expired',
        'suspended',
        'provider_unknown',
    ]
    send_ready: bool = Field(..., alias='sendReady')
    reasons: list[str] = Field(..., max_length=20)
    evaluated_at: AwareDatetime = Field(..., alias='evaluatedAt')


class SenderBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    service_ref: str = Field(
        ..., alias='serviceRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    state: Literal['verified', 'reconciliation_required']
    webhook_state: Literal['verified', 'mismatch'] = Field(..., alias='webhookState')
    send_ready: bool = Field(..., alias='sendReady')
    reasons: list[str] = Field(..., max_length=20)
    verified_at: AwareDatetime = Field(..., alias='verifiedAt')


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    sms: bool
    mms: bool
    voice: bool


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    number_ref: str = Field(
        ..., alias='numberRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    number_display: str | None = Field(
        None, alias='numberDisplay', max_length=40, min_length=1
    )
    lifecycle_state: (
        Literal[
            'owned',
            'release_frozen',
            'release_pending',
            'reconciliation_required',
            'released',
        ]
        | None
    ) = Field(None, alias='lifecycleState')
    registration: Registration | None = None
    sender_binding: SenderBinding | None = Field(None, alias='senderBinding')
    capabilities: Capabilities | None = None
    inbound_ready: bool | None = Field(None, alias='inboundReady')
    outbound_ready: bool = Field(..., alias='outboundReady')
    reasons: list[str] = Field(..., max_length=40)
    last_verified_at: AwareDatetime = Field(..., alias='lastVerifiedAt')


class ResultDigest(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str = Field(..., pattern='^[a-z][a-z0-9_]{2,80}$')
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never', 'safe_read', 'same_identity_after_reconciliation', 'new_review'
    ] = Field(..., alias='retryClass')
    trace_ref: str | None = Field(
        None, alias='traceRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class NextAction(RootModel[str]):
    root: str = Field(..., max_length=240, min_length=1)


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class NextCursor(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._~:-]{1,512}$')


class Offload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantNumberStatusOutput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    data: Data
    receipt: Receipt | None = None
    meta: Meta
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    offload: Offload | None = None
    truncated: bool
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Receipt1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class Meta1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class Offload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantNumberStatusOutput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    receipt: Receipt1 | None = None
    meta: Meta1
    resource_uri: str = Field(..., alias='resourceUri', max_length=240)
    offload: Offload1
    truncated: Literal[True]
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Error2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Literal[
        'not_authenticated',
        'validation_failed',
        'idempotency_key_invalid',
        'request_too_large',
        'not_found',
        'registration_review_expired',
        'schedule_confirmation_conflict',
        'response_too_large',
        'service_not_configured',
        'invalid_caller',
        'invalid_request',
        'policy_denied',
        'approval_required',
        'assistant_service_failed',
        'assistant_request_cancelled',
        'assistant_request_failed',
        'assistant_resource_failed',
        'assistant_response_invalid',
        'assistant_response_rejected',
        'assistant_response_too_large',
        'mcp_http_error',
        'mcp_request_timeout',
        'response_lost',
        'service_unavailable',
        'idempotency_conflict',
        'idempotency_in_progress',
    ]
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never',
        'safe_read',
        'receipt_lookup',
        'reconcile_first',
        'same_identity_after_reconciliation',
        'new_review',
    ] = Field(..., alias='retryClass')
    request_ref: str | None = Field(
        None, alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class AssistantNumberStatusOutput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[False]
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    truncated: Literal[False]
    untrusted_content: bool = Field(..., alias='untrustedContent')
    error: Error2


class AssistantNumberStatusOutput(
    RootModel[
        AssistantNumberStatusOutput1
        | AssistantNumberStatusOutput2
        | AssistantNumberStatusOutput3
    ]
):
    root: (
        AssistantNumberStatusOutput1
        | AssistantNumberStatusOutput2
        | AssistantNumberStatusOutput3
    )


class AssistantNumberStatusModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: AssistantNumberStatusInput
    output: AssistantNumberStatusOutput
