# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class HarvestPaaInput(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pages: int | None = Field(
        1,
        description='Organic result pages to capture. Default 1, maximum 2. Page 2 is captured when available before harvesting PAA on the original first page; it does not add a second PAA graph. Pagination output reports the pages actually captured.',
        ge=1,
        le=2,
    )
    query: str = Field(
        ...,
        description='The search topic, exactly as it should be searched, e.g. "best hvac company in Denver". Include the place here when you want it in the search terms — the server sends your query to Google unchanged and never adds or removes a location.',
        min_length=1,
    )
    location: str | None = Field(
        None,
        description='Where Google should think the searcher is, e.g. "Denver, CO". Sets the Google UULE parameter only — it never changes your query text and never selects a proxy. To put the place in the search terms too, write it into query.',
    )
    max_questions: int | None = Field(
        30,
        alias='maxQuestions',
        description='PAA questions to extract. Default 30, maximum 200. Use 10 for quick probes, 100-200 for deep research. Billed per extracted question; unused hold refunded.',
        ge=1,
        le=200,
    )
    gl: str | None = Field(
        'us',
        description='Google country code inferred from location or user language.',
        max_length=2,
        min_length=2,
    )
    hl: str | None = Field(
        'en',
        description='Google interface/content language inferred from the user request.',
    )
    device: Literal['desktop', 'mobile'] | None = Field(
        'desktop',
        description='SERP device context. Use mobile only for mobile rankings.',
    )
    idempotency_key: str | None = Field(
        None,
        alias='idempotencyKey',
        description='Optional duplicate-start key. Reuse it only after an uncertain or lost response to the same logical call; use a new key for an intentional retry after a terminal failure. This is not the run identifier.',
        max_length=200,
        min_length=8,
    )
    serp_identity: str | None = Field(
        None,
        alias='serpIdentity',
        description='Optional persistent SERP identity created with serp_identity_create. Reuses the same saved browser state and fixed network address across calls.',
        pattern='^[a-z0-9][a-z0-9_-]{0,63}$',
    )
    include_all_serp_features: bool | None = Field(
        False,
        alias='includeAllSerpFeatures',
        description='Capture every optional same-page SERP surface: local pack, forums, videos, AI Overview/AI Mode, and What People Are Saying.',
    )
    include_local_pack: bool | None = Field(
        False,
        alias='includeLocalPack',
        description='Include Google local/map-pack businesses and merge their entity IDs.',
    )
    include_forums: bool | None = Field(
        False,
        alias='includeForums',
        description='Include Discussions and Forums results.',
    )
    include_videos: bool | None = Field(
        False,
        alias='includeVideos',
        description='Include video result names and URLs present on the original SERP.',
    )
    include_ai_overview: bool | None = Field(
        False,
        alias='includeAiOverview',
        description='Include AI Overview and AI Mode text and citations when present.',
    )
    include_what_people_saying: bool | None = Field(
        False,
        alias='includeWhatPeopleSaying',
        description='Include the What People Are Saying social surface when present.',
    )


class PaaLifecycle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_questions: int = Field(
        ..., alias='requestedQuestions', ge=0, le=9007199254740991
    )
    questions_found: int = Field(..., alias='questionsFound', ge=0, le=9007199254740991)
    target_status: Literal['met', 'not_met'] = Field(..., alias='targetStatus')
    discovery_status: Literal[
        'in_progress',
        'target_reached',
        'frontier_exhausted',
        'no_paa_observed',
        'interrupted',
        'recovery_exhausted',
    ] = Field(..., alias='discoveryStatus')
    material_status: Literal['complete', 'partial'] = Field(..., alias='materialStatus')
    completion_reason: str = Field(..., alias='completionReason')
    automatic_retries: int = Field(
        ..., alias='automaticRetries', ge=0, le=9007199254740991
    )
    known_questions: int = Field(..., alias='knownQuestions', ge=0, le=9007199254740991)
    processed_questions: int = Field(
        ..., alias='processedQuestions', ge=0, le=9007199254740991
    )
    failed_interactions: int = Field(
        ..., alias='failedInteractions', ge=0, le=9007199254740991
    )
    no_growth_confirmations: int = Field(
        ..., alias='noGrowthConfirmations', ge=0, le=9007199254740991
    )
    visible_controls: int = Field(
        ..., alias='visibleControls', ge=0, le=9007199254740991
    )
    eligible_controls: int = Field(
        ..., alias='eligibleControls', ge=0, le=9007199254740991
    )
    dispatched_interactions: int = Field(
        ..., alias='dispatchedInteractions', ge=0, le=9007199254740991
    )
    confirmed_interactions: int = Field(
        ..., alias='confirmedInteractions', ge=0, le=9007199254740991
    )
    unconfirmed_interactions: int = Field(
        ..., alias='unconfirmedInteractions', ge=0, le=9007199254740991
    )


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_pages: Literal[1, 2] = Field(..., alias='requestedPages')
    captured_pages: Literal[1, 2] = Field(..., alias='capturedPages')
    page2_status: Literal[
        'not_requested', 'not_attempted', 'captured', 'unavailable', 'failed'
    ] = Field(..., alias='page2Status')
    page1_organic_count: int = Field(
        ..., alias='page1OrganicCount', ge=0, le=9007199254740991
    )
    page2_organic_count: int = Field(
        ..., alias='page2OrganicCount', ge=0, le=9007199254740991
    )
    failure_code: (
        Literal[
            'missing_next',
            'invalid_next',
            'empty_page',
            'captcha',
            'timeout',
            'navigation_error',
            'unsupported_driver',
        ]
        | None
    ) = Field(None, alias='failureCode')


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    url: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )
    title: str | None
    site: str | None


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    question_id: str = Field(..., alias='questionId')
    google_link_id: str | None = Field(..., alias='googleLinkId')
    google_evidence_id: str | None = Field(..., alias='googleEvidenceId')
    question: str
    answer: str | None
    sources: list[Source]
    source_title: str | None = Field(..., alias='sourceTitle')
    source_site: str | None = Field(..., alias='sourceSite')
    source_url: str | None = Field(..., alias='sourceUrl')


class OrganicResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    position: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    title: str
    url: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )
    domain: str
    snippet: str | None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    text: str
    href: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )


class AiOverview(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    detected: bool
    text: str | None
    citations: list[Citation]
    expanded: bool
    fully_expanded: bool = Field(..., alias='fullyExpanded')
    sections: list[str]
    share_url: str | None = Field(None, alias='shareUrl')


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str
    kg_id: str | None = Field(..., alias='kgId')
    cid: str | None
    gcid: str | None


class EntityIds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    entities: list[Entity] = Field(
        ...,
        description='Entities named on the page with their kgId/cid/gcid. Flat lists below are the same IDs deduplicated, kept for backward compatibility.',
    )
    kg_ids: list[str] = Field(..., alias='kgIds')
    cids: list[str]
    gcids: list[str]


class DurationMs(RootModel[float]):
    root: float = Field(..., ge=0.0)


class HarvestPaaOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    query: str
    location: str | None
    question_count: int = Field(..., alias='questionCount', ge=0, le=9007199254740991)
    completion_status: str | None = Field(..., alias='completionStatus')
    result_quality: str | None = Field(..., alias='resultQuality')
    degraded_result: bool | None = Field(..., alias='degradedResult')
    degradation_reasons: list[str] = Field(..., alias='degradationReasons')
    retry_recommended: bool | None = Field(..., alias='retryRecommended')
    paa_lifecycle: PaaLifecycle | None = Field(..., alias='paaLifecycle')
    pagination: Pagination | None
    questions: list[Question]
    organic_results: list[OrganicResult] = Field(..., alias='organicResults')
    ai_overview: AiOverview | None = Field(..., alias='aiOverview')
    entity_ids: EntityIds | None = Field(..., alias='entityIds')
    duration_ms: DurationMs | None = Field(..., alias='durationMs')


class HarvestPaaModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: HarvestPaaInput
    output: HarvestPaaOutput
