# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class HarvestPaaStatusInput(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    job_id: str = Field(
        ...,
        alias='jobId',
        description='The jobId returned by harvest_paa_start.',
        max_length=200,
        min_length=1,
    )


class Status(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['pending']
    terminal: Literal[False]
    poll_after_seconds: int = Field(
        ..., alias='pollAfterSeconds', ge=1, le=9007199254740991
    )
    retry_guidance: str = Field(..., alias='retryGuidance')


class Status1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['running']
    terminal: Literal[False]
    poll_after_seconds: int = Field(
        ..., alias='pollAfterSeconds', ge=1, le=9007199254740991
    )
    retry_guidance: str = Field(..., alias='retryGuidance')


class Status2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['done']
    terminal: Literal[True]
    poll_after_seconds: None = Field(..., alias='pollAfterSeconds')
    retry_guidance: str = Field(..., alias='retryGuidance')


class Status3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['failed']
    terminal: Literal[True]
    poll_after_seconds: None = Field(..., alias='pollAfterSeconds')
    retry_guidance: str = Field(..., alias='retryGuidance')


class Status4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['cancelled']
    terminal: Literal[True]
    poll_after_seconds: None = Field(..., alias='pollAfterSeconds')
    retry_guidance: str = Field(..., alias='retryGuidance')


class RequestedQuestions(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class Lifecycle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_questions: int = Field(
        ..., alias='requestedQuestions', ge=0, le=9007199254740991
    )
    questions_found: int = Field(..., alias='questionsFound', ge=0, le=9007199254740991)
    target_status: Literal['met', 'not_met'] = Field(..., alias='targetStatus')
    discovery_status: Literal[
        'in_progress',
        'target_reached',
        'frontier_exhausted',
        'no_paa_observed',
        'interrupted',
        'recovery_exhausted',
    ] = Field(..., alias='discoveryStatus')
    material_status: Literal['complete', 'partial'] = Field(..., alias='materialStatus')
    completion_reason: str = Field(..., alias='completionReason')
    automatic_retries: int = Field(
        ..., alias='automaticRetries', ge=0, le=9007199254740991
    )
    known_questions: int = Field(..., alias='knownQuestions', ge=0, le=9007199254740991)
    processed_questions: int = Field(
        ..., alias='processedQuestions', ge=0, le=9007199254740991
    )
    failed_interactions: int = Field(
        ..., alias='failedInteractions', ge=0, le=9007199254740991
    )
    no_growth_confirmations: int = Field(
        ..., alias='noGrowthConfirmations', ge=0, le=9007199254740991
    )
    visible_controls: int = Field(
        ..., alias='visibleControls', ge=0, le=9007199254740991
    )
    eligible_controls: int = Field(
        ..., alias='eligibleControls', ge=0, le=9007199254740991
    )
    dispatched_interactions: int = Field(
        ..., alias='dispatchedInteractions', ge=0, le=9007199254740991
    )
    confirmed_interactions: int = Field(
        ..., alias='confirmedInteractions', ge=0, le=9007199254740991
    )
    unconfirmed_interactions: int = Field(
        ..., alias='unconfirmedInteractions', ge=0, le=9007199254740991
    )


class InteractionSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    observations: int = Field(..., ge=0, le=9007199254740991)
    dispatched: int = Field(..., ge=0, le=9007199254740991)
    confirmed: int = Field(..., ge=0, le=9007199254740991)
    unconfirmed: int = Field(..., ge=0, le=9007199254740991)
    dispatch_failures: int = Field(
        ..., alias='dispatchFailures', ge=0, le=9007199254740991
    )
    confirmed_without_dispatch_ack: int = Field(
        ..., alias='confirmedWithoutDispatchAck', ge=0, le=9007199254740991
    )
    expanded_signals: int = Field(
        ..., alias='expandedSignals', ge=0, le=9007199254740991
    )
    answer_signals: int = Field(..., alias='answerSignals', ge=0, le=9007199254740991)
    source_signals: int = Field(..., alias='sourceSignals', ge=0, le=9007199254740991)
    question_growth_batches: int = Field(
        ..., alias='questionGrowthBatches', ge=0, le=9007199254740991
    )
    checkpoint700ms: int = Field(..., ge=0, le=9007199254740991)
    checkpoint1000ms: int = Field(..., ge=0, le=9007199254740991)
    checkpoint1400ms: int = Field(..., ge=0, le=9007199254740991)


class ConfirmedAtMs(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class RecentInteraction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    question_id: str = Field(..., alias='questionId')
    question: str
    batch_number: int = Field(..., alias='batchNumber', ge=0, le=9007199254740991)
    control_attempt: int = Field(..., alias='controlAttempt', ge=0, le=9007199254740991)
    observed_at: str | None = Field(..., alias='observedAt')
    dispatched: bool
    outcome: Literal['confirmed', 'unconfirmed', 'dispatch_failed']
    confirmation_signals: list[
        Literal['expanded', 'answer', 'source', 'question_growth']
    ] = Field(..., alias='confirmationSignals')
    confirmation_checkpoint_ms: Literal[700, 1000, 1400] | None = Field(
        ..., alias='confirmationCheckpointMs'
    )
    confirmed_at_ms: ConfirmedAtMs | None = Field(..., alias='confirmedAtMs')
    dispatch_duration_ms: int = Field(
        ..., alias='dispatchDurationMs', ge=0, le=9007199254740991
    )
    total_duration_ms: int = Field(
        ..., alias='totalDurationMs', ge=0, le=9007199254740991
    )
    before_question_count: int = Field(
        ..., alias='beforeQuestionCount', ge=0, le=9007199254740991
    )
    after_question_count: int = Field(
        ..., alias='afterQuestionCount', ge=0, le=9007199254740991
    )
    new_question_count: int = Field(
        ..., alias='newQuestionCount', ge=0, le=9007199254740991
    )
    expanded_before: bool = Field(..., alias='expandedBefore')
    expanded_after: bool = Field(..., alias='expandedAfter')
    answer_observed: bool = Field(..., alias='answerObserved')
    source_count: int = Field(..., alias='sourceCount', ge=0, le=9007199254740991)
    error_code: (
        Literal[
            'click_failed',
            'click_ack_timeout',
            'control_missing',
            'confirmation_timeout',
        ]
        | None
    ) = Field(..., alias='errorCode')


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_questions: RequestedQuestions | None = Field(
        ..., alias='requestedQuestions'
    )
    captured_questions: int = Field(
        ..., alias='capturedQuestions', ge=0, le=9007199254740991
    )
    answered_questions: int = Field(
        ..., alias='answeredQuestions', ge=0, le=9007199254740991
    )
    sourced_questions: int = Field(
        ..., alias='sourcedQuestions', ge=0, le=9007199254740991
    )
    missing_answers: int = Field(..., alias='missingAnswers', ge=0, le=9007199254740991)
    missing_sources: int = Field(..., alias='missingSources', ge=0, le=9007199254740991)
    lifecycle: Lifecycle | None
    interaction_summary: InteractionSummary = Field(..., alias='interactionSummary')
    recent_interactions: list[RecentInteraction] = Field(
        ..., alias='recentInteractions', max_length=20
    )


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_pages: Literal[1, 2] = Field(..., alias='requestedPages')
    captured_pages: Literal[1, 2] = Field(..., alias='capturedPages')
    page2_status: Literal[
        'not_requested', 'not_attempted', 'captured', 'unavailable', 'failed'
    ] = Field(..., alias='page2Status')
    page1_organic_count: int = Field(
        ..., alias='page1OrganicCount', ge=0, le=9007199254740991
    )
    page2_organic_count: int = Field(
        ..., alias='page2OrganicCount', ge=0, le=9007199254740991
    )
    failure_code: (
        Literal[
            'missing_next',
            'invalid_next',
            'empty_page',
            'captcha',
            'timeout',
            'navigation_error',
            'unsupported_driver',
        ]
        | None
    ) = Field(None, alias='failureCode')


class PaaLifecycle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    requested_questions: int = Field(
        ..., alias='requestedQuestions', ge=0, le=9007199254740991
    )
    questions_found: int = Field(..., alias='questionsFound', ge=0, le=9007199254740991)
    target_status: Literal['met', 'not_met'] = Field(..., alias='targetStatus')
    discovery_status: Literal[
        'in_progress',
        'target_reached',
        'frontier_exhausted',
        'no_paa_observed',
        'interrupted',
        'recovery_exhausted',
    ] = Field(..., alias='discoveryStatus')
    material_status: Literal['complete', 'partial'] = Field(..., alias='materialStatus')
    completion_reason: str = Field(..., alias='completionReason')
    automatic_retries: int = Field(
        ..., alias='automaticRetries', ge=0, le=9007199254740991
    )
    known_questions: int = Field(..., alias='knownQuestions', ge=0, le=9007199254740991)
    processed_questions: int = Field(
        ..., alias='processedQuestions', ge=0, le=9007199254740991
    )
    failed_interactions: int = Field(
        ..., alias='failedInteractions', ge=0, le=9007199254740991
    )
    no_growth_confirmations: int = Field(
        ..., alias='noGrowthConfirmations', ge=0, le=9007199254740991
    )
    visible_controls: int = Field(
        ..., alias='visibleControls', ge=0, le=9007199254740991
    )
    eligible_controls: int = Field(
        ..., alias='eligibleControls', ge=0, le=9007199254740991
    )
    dispatched_interactions: int = Field(
        ..., alias='dispatchedInteractions', ge=0, le=9007199254740991
    )
    confirmed_interactions: int = Field(
        ..., alias='confirmedInteractions', ge=0, le=9007199254740991
    )
    unconfirmed_interactions: int = Field(
        ..., alias='unconfirmedInteractions', ge=0, le=9007199254740991
    )


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    url: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )
    title: str | None
    site: str | None


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    question_id: str = Field(..., alias='questionId')
    google_link_id: str | None = Field(..., alias='googleLinkId')
    google_evidence_id: str | None = Field(..., alias='googleEvidenceId')
    question: str
    answer: str | None
    sources: list[Source]
    source_title: str | None = Field(..., alias='sourceTitle')
    source_site: str | None = Field(..., alias='sourceSite')
    source_url: str | None = Field(..., alias='sourceUrl')


class OrganicResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    position: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    title: str
    url: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )
    domain: str
    snippet: str | None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    text: str
    href: str
    raw_url: str = Field(..., alias='rawUrl')
    resolved_url: str | None = Field(..., alias='resolvedUrl')
    link_type: Literal['plain', 'google_url_redirect', 'google_goto_redirect'] = Field(
        ..., alias='linkType'
    )
    resolution_status: Literal['not_needed', 'resolved', 'unresolved', 'rejected'] = (
        Field(..., alias='resolutionStatus')
    )


class AiOverview(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    detected: bool
    text: str | None
    citations: list[Citation]
    expanded: bool
    fully_expanded: bool = Field(..., alias='fullyExpanded')
    sections: list[str]
    share_url: str | None = Field(None, alias='shareUrl')


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str
    kg_id: str | None = Field(..., alias='kgId')
    cid: str | None
    gcid: str | None


class EntityIds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    entities: list[Entity] = Field(
        ...,
        description='Entities named on the page with their kgId/cid/gcid. Flat lists below are the same IDs deduplicated, kept for backward compatibility.',
    )
    kg_ids: list[str] = Field(..., alias='kgIds')
    cids: list[str]
    gcids: list[str]


class Result(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pagination: Pagination | None
    completion_status: str | None = Field(..., alias='completionStatus')
    result_quality: str | None = Field(..., alias='resultQuality')
    retry_recommended: bool | None = Field(..., alias='retryRecommended')
    paa_lifecycle: PaaLifecycle | None = Field(..., alias='paaLifecycle')
    question_count: int = Field(..., alias='questionCount', ge=0, le=9007199254740991)
    questions: list[Question]
    organic_results: list[OrganicResult] = Field(..., alias='organicResults')
    ai_overview: AiOverview | None = Field(..., alias='aiOverview')
    entity_ids: EntityIds | None = Field(..., alias='entityIds')


class HoldMc(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class BilledMc(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class RefundMc(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class Billing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['held', 'settled', 'refund_pending', 'refunded', 'unknown']
    hold_mc: HoldMc | None = Field(..., alias='holdMc')
    billed_mc: BilledMc | None = Field(..., alias='billedMc')
    refund_mc: RefundMc | None = Field(..., alias='refundMc')


class HarvestPaaStatusOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    job_id: str = Field(..., alias='jobId')
    operation_id: str = Field(..., alias='operationId')
    task_id: str = Field(..., alias='taskId')
    status: Status | Status1 | Status2 | Status3 | Status4
    replayed: bool
    progress: Progress
    result: Result | None
    billing: Billing


class HarvestPaaStatusModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: HarvestPaaStatusInput
    output: HarvestPaaStatusOutput
