from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field


class MapsPlaceResumeInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    run_id: str = Field(..., alias="runId", description="Partial or reconciled interrupted Maps place run to resume.")
    resume_idempotency_key: str = Field(..., alias="resumeIdempotencyKey", description="A new key for this explicit attempt; reuse the same key to read its status.")


class MapsPlaceResumeOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    run_id: str | None = Field(None, alias="runId", description="")
    run_status: Literal['queued', 'running', 'interrupted', 'complete', 'partial', 'failed', 'cancelled'] | None = Field(None, alias="runStatus", description="")
    verified: bool | None = Field(None, alias="verified", description="")
    checkpoint_revision: int | None = Field(None, alias="checkpointRevision", description="")
    completed_fields: list[str] | None = Field(None, alias="completedFields", description="")
    pending_fields: list[str] | None = Field(None, alias="pendingFields", description="")
    unavailable_fields: list[str] | None = Field(None, alias="unavailableFields", description="")
    requested_max_reviews: int | None = Field(None, alias="requestedMaxReviews", description="")
    requested_max_images: int | None = Field(None, alias="requestedMaxImages", description="")
    images_collected: int | None = Field(None, alias="imagesCollected", description="")
    billing_state: str | None = Field(None, alias="billingState", description="")
    status_path: str | None = Field(None, alias="statusPath", description="")
    reviews_next_cursor: Any | None = Field(None, alias="reviewsNextCursor", description="")
    images_next_cursor: Any | None = Field(None, alias="imagesNextCursor", description="")
    maximum_authorization_mc: int | None = Field(None, alias="maximumAuthorizationMc", description="")
    provider: str | None = Field(None, alias="provider", description="")
    fallback_from: str | None = Field(None, alias="fallbackFrom", description="")
    acquisition_provider: str | None = Field(None, alias="acquisitionProvider", description="")
    name: Any | None = Field(None, alias="name", description="")
    place_url: Any | None = Field(None, alias="placeUrl", description="")
    rating: Any | None = Field(None, alias="rating", description="")
    review_count: Any | None = Field(None, alias="reviewCount", description="")
    category: Any | None = Field(None, alias="category", description="")
    address: Any | None = Field(None, alias="address", description="")
    phone: Any | None = Field(None, alias="phone", description="")
    website: Any | None = Field(None, alias="website", description="")
    hours_summary: Any | None = Field(None, alias="hoursSummary", description="")
    hours_table: list[dict[str, Any]] | None = Field(None, alias="hoursTable", description="")
    plus_code: Any | None = Field(None, alias="plusCode", description="")
    booking_url: Any | None = Field(None, alias="bookingUrl", description="")
    kgmid: Any | None = Field(None, alias="kgmid", description="")
    cid_decimal: Any | None = Field(None, alias="cidDecimal", description="")
    cid_url: Any | None = Field(None, alias="cidUrl", description="")
    lat: Any | None = Field(None, alias="lat", description="")
    lng: Any | None = Field(None, alias="lng", description="")
    reviews_status: str | None = Field(None, alias="reviewsStatus", description="")
    reviews_collected: int | None = Field(None, alias="reviewsCollected", description="")
    reviews: list[dict[str, Any]] | None = Field(None, alias="reviews", description="")
    review_histogram: list[dict[str, Any]] | None = Field(None, alias="reviewHistogram", description="")
    review_topics: list[dict[str, Any]] | None = Field(None, alias="reviewTopics", description="")
    services: list[str] | None = Field(None, alias="services", description="")
    areas_served: list[str] | None = Field(None, alias="areasServed", description="")
    services_status: str | None = Field(None, alias="servicesStatus", description="")
    about_attributes: list[dict[str, Any]] | None = Field(None, alias="aboutAttributes", description="")
    media: dict[str, Any] | None = Field(None, alias="media", description="")
