from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field


class MapsPlaceIntelInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    business_name: str = Field(..., alias="businessName", description="Business name only, e.g. \"Elite Roofing\" (not \"Elite Roofing Denver CO\" — put the city in location).")
    location: str = Field(..., alias="location", description="City/region/country where the business should be searched, e.g. \"Denver, CO\".")
    gl: str | None = Field(None, alias="gl", description="Google country code inferred from location.")
    hl: str | None = Field(None, alias="hl", description="Language inferred from user request.")
    include_reviews: bool | None = Field(None, alias="includeReviews", description="Fetch individual review cards — for reviews, customer pain, complaints, or praise themes.")
    max_reviews: int | None = Field(None, alias="maxReviews", description="Max review cards when includeReviews is true. Default 50, maximum 500.")
    include_services: bool | None = Field(None, alias="includeServices", description="Collect the exact business's configured services and areas served when available. These fields are absent on some profiles.")
    include_images: bool | None = Field(None, alias="includeImages", description="Collect Google Maps listing photos, download them, and return an AI-readable manifest plus an owner-scoped ZIP artifact. The gallery is scrolled until quiescent or maxImages is reached.")
    include: list[Literal['core', 'hours', 'services', 'areasServed', 'reviews', 'images', 'all']] | None = Field(None, alias="include", description="Requested place field groups. all requests every supported group while maxReviews and maxImages still cap collection. Existing includeReviews, includeServices, and includeImages flags remain valid.")
    image_scope: Literal['owner', 'all'] | None = Field(None, alias="imageScope", description="owner collects only the Google Maps By owner gallery. all collects the full gallery and labels exact owner matches versus other/unknown media.")
    max_images: int | None = Field(None, alias="maxImages", description="Maximum photos to collect when includeImages is true. Default 100, maximum 250.")
    max_inline_images: int | None = Field(None, alias="maxInlineImages", description="Maximum downloaded photos attached as MCP image blocks for direct AI vision. The ZIP and structured manifest still contain the wider result.")


class MapsPlaceIntelOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    run_id: str | None = Field(None, alias="runId", description="")
    run_status: Literal['queued', 'running', 'interrupted', 'complete', 'partial', 'failed', 'cancelled'] | None = Field(None, alias="runStatus", description="")
    verified: bool | None = Field(None, alias="verified", description="")
    checkpoint_revision: int | None = Field(None, alias="checkpointRevision", description="")
    completed_fields: list[str] | None = Field(None, alias="completedFields", description="")
    pending_fields: list[str] | None = Field(None, alias="pendingFields", description="")
    unavailable_fields: list[str] | None = Field(None, alias="unavailableFields", description="")
    requested_max_reviews: int | None = Field(None, alias="requestedMaxReviews", description="")
    requested_max_images: int | None = Field(None, alias="requestedMaxImages", description="")
    images_collected: int | None = Field(None, alias="imagesCollected", description="")
    billing_state: str | None = Field(None, alias="billingState", description="")
    status_path: str | None = Field(None, alias="statusPath", description="")
    reviews_next_cursor: Any | None = Field(None, alias="reviewsNextCursor", description="")
    images_next_cursor: Any | None = Field(None, alias="imagesNextCursor", description="")
    maximum_authorization_mc: int | None = Field(None, alias="maximumAuthorizationMc", description="")
    provider: str | None = Field(None, alias="provider", description="")
    fallback_from: str | None = Field(None, alias="fallbackFrom", description="")
    acquisition_provider: str | None = Field(None, alias="acquisitionProvider", description="")
    name: Any | None = Field(None, alias="name", description="")
    place_url: Any | None = Field(None, alias="placeUrl", description="")
    rating: Any | None = Field(None, alias="rating", description="")
    review_count: Any | None = Field(None, alias="reviewCount", description="")
    category: Any | None = Field(None, alias="category", description="")
    address: Any | None = Field(None, alias="address", description="")
    phone: Any | None = Field(None, alias="phone", description="")
    website: Any | None = Field(None, alias="website", description="")
    hours_summary: Any | None = Field(None, alias="hoursSummary", description="")
    hours_table: list[dict[str, Any]] | None = Field(None, alias="hoursTable", description="")
    plus_code: Any | None = Field(None, alias="plusCode", description="")
    booking_url: Any | None = Field(None, alias="bookingUrl", description="")
    kgmid: Any | None = Field(None, alias="kgmid", description="")
    cid_decimal: Any | None = Field(None, alias="cidDecimal", description="")
    cid_url: Any | None = Field(None, alias="cidUrl", description="")
    lat: Any | None = Field(None, alias="lat", description="")
    lng: Any | None = Field(None, alias="lng", description="")
    reviews_status: str | None = Field(None, alias="reviewsStatus", description="")
    reviews_collected: int | None = Field(None, alias="reviewsCollected", description="")
    reviews: list[dict[str, Any]] | None = Field(None, alias="reviews", description="")
    review_histogram: list[dict[str, Any]] | None = Field(None, alias="reviewHistogram", description="")
    review_topics: list[dict[str, Any]] | None = Field(None, alias="reviewTopics", description="")
    services: list[str] | None = Field(None, alias="services", description="")
    areas_served: list[str] | None = Field(None, alias="areasServed", description="")
    services_status: str | None = Field(None, alias="servicesStatus", description="")
    about_attributes: list[dict[str, Any]] | None = Field(None, alias="aboutAttributes", description="")
    media: dict[str, Any] | None = Field(None, alias="media", description="")
