# generated by datamodel-codegen:
#   filename:  scraper.openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Error(BaseModel):
    error: str
    error_code: str | None = None
    message: str | None = None


class StructuredError(BaseModel):
    """
    Shared structured error shape used by SERP Intelligence endpoints.
    """

    error_code: str
    error_type: str
    message: str
    retryable: bool
    attempts: list[dict[str, Any]] | None = None


class Error1(Enum):
    insufficient_balance = 'insufficient_balance'


class ErrorCode(Enum):
    insufficient_balance = 'insufficient_balance'


class InsufficientBalanceError(BaseModel):
    error: Error1
    error_code: ErrorCode
    message: str
    balance_credits: float
    required_credits: float
    topup_url: AnyUrl


class ErrorCode1(Enum):
    concurrency_limit_exceeded = 'concurrency_limit_exceeded'


class ErrorType(Enum):
    concurrency_limit = 'concurrency_limit'


class ConcurrencyLimitError(BaseModel):
    error: str | None = None
    message: str
    error_code: ErrorCode1
    error_type: ErrorType | None = None
    retryable: bool | None = None
    active: int
    limit: int
    operation: str
    upgrade_url: AnyUrl | None = None
    upgrade_command: str | None = Field(
        None, description='CLI command to buy an extra concurrency slot.'
    )


class Device(Enum):
    desktop = 'desktop'
    mobile = 'mobile'


class ProxyMode(Enum):
    location = 'location'
    configured = 'configured'
    none = 'none'


class HarvestSyncRequest(BaseModel):
    query: str = Field(..., description='Search query.')
    location: str | None = Field(None, description='e.g. "Austin, TX".')
    depth: int | None = Field(
        4,
        description='PAA drill-down depth. Ignored when serpOnly is true.',
        ge=1,
        le=4,
    )
    maxQuestions: int | None = Field(
        30,
        description='Max PAA questions to harvest. Ignored when serpOnly is true.',
        ge=1,
    )
    gl: str | None = Field('us', description='Google country code.')
    hl: str | None = Field('en', description='Google language code.')
    device: Device | None = 'desktop'
    proxyMode: ProxyMode | None = 'none'
    proxyZip: str | None = Field(
        None, description='US ZIP to localize the proxy egress to.', pattern='^\\d{5}$'
    )
    pages: int | None = Field(
        1, description='Organic result pages to fetch.', ge=1, le=2
    )
    serpOnly: bool | None = Field(
        False,
        description='true = pure SERP call (search_serp); false = full PAA harvest.',
    )
    debug: bool | None = False


class Status(Enum):
    done = 'done'
    cancelled = 'cancelled'
    failed = 'failed'


class HarvestSyncResponse(BaseModel):
    job_id: str
    status: Status
    result: dict[str, Any] | None = Field(
        None, description='Present when status is done — SERP/PAA harvest result.'
    )
    attempts: list[dict[str, Any]] | None = None
    error: str | None = None


class JobRecord(BaseModel):
    id: str | None = None
    status: str | None = None
    query: str | None = None
    result: dict[str, Any] | None = None
    attempts: list[dict[str, Any]] | None = None
    created_at: str | None = None


class ScreenshotDevice(Enum):
    desktop = 'desktop'
    mobile = 'mobile'


class MediaType(Enum):
    image = 'image'
    video = 'video'
    audio = 'audio'


class ExtractUrlRequest(BaseModel):
    url: AnyUrl
    screenshot: bool | None = False
    screenshotDevice: ScreenshotDevice | None = 'desktop'
    extractBranding: bool | None = Field(
        False, description='Extract brand colors/fonts/logo.'
    )
    downloadMedia: bool | None = False
    mediaTypes: list[MediaType] | None = None
    allowLocal: bool | None = False
    depositToVault: bool | None = Field(
        False, description='Save the extracted content into an mcp-memory vault.'
    )
    vaultName: str | None = Field(None, max_length=120)


class Screenshot(BaseModel):
    base64: str | None = None
    sizeBytes: int | None = None
    device: str | None = None


class VaultDepositResult(BaseModel):
    """
    Present on ExtractUrlResponse only when the request set depositToVault: true.
    Result of depositing a scrape into the caller's mcp-memory vault. Falls back to a
    temporary downloadable file (`fileUrl`, expires in 24h) if the vault deposit itself
    fails, so the content is never silently lost.

    """

    deposited: bool = Field(
        ..., description='True if the content was embedded into the vault.'
    )
    vault: str | None = Field(None, description='The vault handle deposited into.')
    noteId: str | None = None
    path: str | None = Field(
        None,
        description='Note path within the vault, addressable via mcpscraper-memory-sdk.',
    )
    chunks: int | None = Field(None, description='Number of embedded chunks created.')
    error: str | None = Field(None, description='Present when deposited is false.')
    fileUrl: str | None = Field(
        None,
        description='Fallback download URL, only present when the vault deposit failed.',
    )
    fileExpiresAt: AwareDatetime | None = Field(
        None, description='Fallback file expiry, only present alongside fileUrl.'
    )


class MapUrlsRequest(BaseModel):
    url: AnyUrl
    maxUrls: int | None = Field(500, ge=1, le=2000)
    concurrency: int | None = Field(12, ge=1, le=20)
    browserFallback: bool | None = Field(
        False, description='Use a real browser session for JS-heavy sites.'
    )
    kernelFallback: bool | None = False


class MapUrlsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    urls: list[str] | None = None


class Format(Enum):
    markdown = 'markdown'
    links = 'links'
    json = 'json'
    images = 'images'
    branding = 'branding'


class ExtractSiteRequest(BaseModel):
    url: AnyUrl
    maxPages: int | None = Field(100, ge=1, le=10000)
    background: bool | None = Field(
        False, description='Enqueue an async crawl instead of waiting inline.'
    )
    rotateProxies: bool | None = False
    rotateProxyEvery: int | None = Field(30, ge=1, le=100)
    browserFallback: bool | None = False
    kernelFallback: bool | None = False
    formats: list[Format] | None = None


class ExtractSiteResponse(BaseModel):
    """
    Full synchronous crawl result.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    pages: list[dict[str, Any]] | None = None


class Status1(Enum):
    pending = 'pending'


class ExtractSiteQueuedResponse(BaseModel):
    jobId: str
    status: Status1
    statusUrl: str


class ExtractSiteStatus(BaseModel):
    jobId: str | None = None
    status: str | None = None
    startUrl: str | None = None
    totalUrls: int | None = None
    doneUrls: int | None = None
    artifacts: list[dict[str, Any]] | None = None
    error: str | None = None
    updatedAt: str | None = None


class Mode(Enum):
    search = 'search'
    channel = 'channel'


class YoutubeHarvestRequest(BaseModel):
    mode: Mode
    query: str | None = Field(None, description='Required when mode is search.')
    channelHandle: str | None = Field(
        None, description='Required when mode is channel — @handle or UC... channel ID.'
    )
    maxVideos: int | None = Field(50, ge=1, le=500)


class Chunk(BaseModel):
    timestamp: list[float] | None = Field(None, max_length=2, min_length=2)
    text: str | None = None


class TranscriptResponse(BaseModel):
    videoId: str | None = None
    text: str | None = None
    chunks: list[Chunk] | None = None
    durationMs: float | None = None
    markdown: str | None = None
    html: str | None = None


class MapsSearchRequest(BaseModel):
    query: str
    location: str | None = None
    gl: str | None = 'us'
    hl: str | None = 'en'
    maxResults: int | None = Field(10, ge=1, le=50)
    proxyMode: ProxyMode | None = 'location'
    proxyZip: str | None = Field(None, pattern='^\\d{5}$')
    debug: bool | None = False


class MapsPlaceRequest(BaseModel):
    businessName: str
    location: str
    gl: str | None = 'us'
    hl: str | None = 'en'
    includeReviews: bool | None = False
    maxReviews: int | None = Field(50, ge=1, le=500)


class SerpIntelligenceCaptureRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str = Field(..., min_length=1)
    location: str | None = None
    gl: str | None = 'us'
    hl: str | None = 'en'
    device: Device | None = 'desktop'
    proxyMode: ProxyMode | None = 'none'
    proxyZip: str | None = Field(None, pattern='^\\d{5}$')
    pages: int | None = Field(1, ge=1, le=2)
    debug: bool | None = False
    includePageSnapshots: bool | None = False
    pageSnapshotLimit: int | None = Field(0, ge=0, le=10)


class SourceKind(Enum):
    organic = 'organic'
    ai_citation = 'ai_citation'
    local_pack_website = 'local_pack_website'
    configured_target = 'configured_target'
    site_subject = 'site_subject'


class Target(BaseModel):
    url: AnyUrl | None = None
    sourceKind: SourceKind | None = 'configured_target'
    sourcePosition: int | None = Field(None, ge=1)


class SerpIntelligencePageSnapshotsRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    urls: list[AnyUrl] = Field(..., max_length=25, min_length=1)
    targets: list[Target] | None = Field(None, max_length=25)
    maxConcurrency: int | None = Field(2, ge=1, le=5)
    timeoutMs: int | None = Field(15000, ge=1000, le=60000)
    debug: bool | None = False


class InlineRating(BaseModel):
    value: str | None = None
    count: str | None = None


class SerpIntelligenceOrganicResult(BaseModel):
    position: int | None = Field(None, ge=1)
    title: str | None = None
    url: str | None = None
    domain: str | None = None
    cite: str | None = None
    snippet: str | None = None
    isRedditStyle: bool | None = None
    inlineRating: InlineRating | None = None


class Surface(Enum):
    web = 'web'
    aim = 'aim'
    unknown = 'unknown'


class Citation(BaseModel):
    text: str | None = None
    href: str | None = None


class AiOverview(BaseModel):
    detected: bool | None = None
    text: str | None = None
    citations: list[Citation] | None = None


class AiMode(BaseModel):
    detected: bool | None = None
    text: str | None = None
    citations: list[Citation] | None = None


class Entity(BaseModel):
    name: str | None = None
    kgId: str | None = None
    cid: str | None = None
    gcid: str | None = None


class EntityIds(BaseModel):
    entities: list[Entity] | None = None
    kgIds: list[str] | None = None
    cids: list[str] | None = None
    gcids: list[str] | None = None


class Stats(BaseModel):
    seed: str | None = None
    totalQuestions: int | None = None
    maxDepthReached: int | None = None
    durationMs: float | None = None
    errorCount: int | None = None


class SerpIntelligenceHarvestResult(BaseModel):
    seed: str | None = None
    location: str | None = None
    extractedAt: str | None = None
    totalQuestions: int | None = None
    surface: Surface | None = None
    aiOverview: AiOverview | None = None
    aiMode: AiMode | None = None
    tree: list[Any] | None = None
    flat: list[Any] | None = None
    videos: list[Any] | None = None
    forums: list[Any] | None = None
    organicResults: list[SerpIntelligenceOrganicResult] | None = None
    localPack: list[Any] | None = None
    entityIds: EntityIds | None = None
    stats: Stats | None = None
    diagnostics: dict[str, Any] | None = None
    whatPeopleSaying: list[Any] | None = None


class Status2(Enum):
    captured = 'captured'
    skipped = 'skipped'
    failed = 'failed'


class FetchedVia(Enum):
    fetch = 'fetch'
    headless = 'headless'
    browser = 'browser'
    mcp = 'mcp'


class Heading(BaseModel):
    level: int | None = None
    text: str | None = None


class Artifact(BaseModel):
    htmlBlobUrl: str | None = None
    textBlobUrl: str | None = None
    markdownBlobUrl: str | None = None
    screenshotBlobUrl: str | None = None
    contentSha256: str | None = None
    capturedAt: str | None = None


class Error2(BaseModel):
    code: str | None = None
    message: str | None = None


class SerpPageSnapshotCapture(BaseModel):
    url: str | None = None
    requestedUrl: str | None = None
    finalUrl: str | None = None
    sourceKind: SourceKind | None = 'configured_target'
    sourcePosition: int | None = None
    status: Status2 | None = None
    fetchedVia: FetchedVia | None = None
    httpStatus: int | None = None
    contentType: str | None = None
    title: str | None = None
    canonicalUrl: str | None = None
    metaDescription: str | None = None
    headings: list[Heading] | None = None
    artifact: Artifact | None = None
    error: Error2 | None = None


class SerpIntelligenceCaptureAttempt(BaseModel):
    attemptNumber: int | None = None
    outcome: str | None = None
    startedAt: str | None = None
    completedAt: str | None = None
    durationMs: float | None = None
    problemCode: str | None = None
    message: str | None = None
    kernelSessionId: str | None = None
    cleanupSucceeded: bool | None = None


class Billing(BaseModel):
    creditsUsed: float | None = None
    requestId: str | None = None
    jobId: str | None = None


class SerpIntelligenceCaptureResponse(BaseModel):
    harvestResult: SerpIntelligenceHarvestResult | None = None
    attempts: list[SerpIntelligenceCaptureAttempt] | None = None
    locationEvidence: dict[str, Any] | None = None
    pageSnapshotArtifacts: list[SerpPageSnapshotCapture] | None = None
    billing: Billing | None = None


class SerpIntelligencePageSnapshotsResponse(BaseModel):
    pageSnapshotArtifacts: list[SerpPageSnapshotCapture] | None = None
    attempts: list[SerpIntelligenceCaptureAttempt] | None = None


class Status3(Enum):
    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    partial = 'partial'
    failed = 'failed'
    cancelled = 'cancelled'


class Artifact1(BaseModel):
    id: str | None = None
    kind: str | None = None
    label: str | None = None
    downloadUrl: str | None = None


class WorkflowRun(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str | None = None
    workflow_id: str | None = None
    status: Status3 | None = None
    input: dict[str, Any] | None = None
    step_index: int | None = None
    created_at: str | None = None
    completed_at: str | None = None
    error_message: str | None = None
    artifacts: list[Artifact1] | None = None


class Step(BaseModel):
    index: int | None = None
    id: str | None = None
    title: str | None = None
    totalSteps: int | None = None
    output: dict[str, Any] | None = None
    warnings: list[str] | None = None


class NextStep(BaseModel):
    index: int | None = None
    id: str | None = None
    title: str | None = None


class WorkflowRunStepResponse(BaseModel):
    run: WorkflowRun | None = None
    summary: dict[str, Any] | None = Field(
        None, description='Present once the run reaches a terminal state.'
    )
    step: Step | None = None
    nextStep: NextStep | None = None
    done: bool | None = None


class Status4(Enum):
    active = 'active'
    paused = 'paused'


class Cadence(Enum):
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'


class WorkflowSchedule(BaseModel):
    id: str | None = None
    workflow_id: str | None = None
    name: str | None = None
    status: Status4 | None = None
    input: dict[str, Any] | None = None
    cadence: Cadence | None = None
    timezone: str | None = None
    webhook_url: str | None = None
    next_run_at: str | None = None


class CallMemoryToolRequest(BaseModel):
    toolName: str = Field(
        ...,
        description='A tool name from contracts/memory.tools.json, e.g. "memory-search".',
    )
    args: dict[str, Any] | None = Field(
        {},
        description="The named tool's input, matching its inputSchema in memory.tools.json.",
    )


class CallMemoryToolResponse(BaseModel):
    """
    Shape depends on the tool called — see its outputSchema in memory.tools.json.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    ok: bool | None = None
    error: str | None = Field(None, description='Present when ok is false.')


class ExtractUrlResponse(BaseModel):
    """
    Spreads the page extraction result plus optional screenshot/branding/media/memory.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    title: str | None = None
    bodyMarkdown: str | None = None
    bodyHtml: str | None = None
    headings: list[dict[str, Any]] | None = None
    screenshot: Screenshot | None = None
    branding: dict[str, Any] | None = None
    media: dict[str, Any] | None = None
    memory: VaultDepositResult | None = None
