# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AssistantDiagnosticsGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )


class SubjectRef(RootModel[str]):
    root: str = Field(..., max_length=160, min_length=1)


class AllowedRead(RootModel[str]):
    root: str = Field(..., max_length=120, min_length=1)


class AllowedAction(RootModel[str]):
    root: str = Field(..., max_length=120, min_length=1)


class NextAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    label: str = Field(..., max_length=120, min_length=1)
    route: str = Field(..., max_length=240, min_length=1)


class SupportReceipt(RootModel[str]):
    root: str = Field(..., max_length=160, min_length=1, pattern='^[A-Za-z0-9._:-]+$')


class ProductAvailability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['productAvailability']
    state: Literal['available', 'degraded', 'unavailable']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class OperatorActivation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['operatorActivation']
    state: Literal['ready', 'in_progress', 'blocked', 'failed', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class AssistantAccount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['assistantAccount']
    state: Literal['active', 'missing', 'paused', 'unavailable', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class ProviderConnection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['providerConnections']
    state: Literal['connected', 'pending', 'disconnected', 'needs_attention', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class SenderRegistration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['senderRegistration']
    state: Literal[
        'not_started',
        'draft',
        'submitted',
        'in_review',
        'approved',
        'rejected',
        'suspended',
        'unknown',
    ]
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class SenderBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['senderBinding']
    state: Literal['missing', 'pending', 'verified', 'failed', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class RecipientEnrollment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['recipientEnrollment']
    state: Literal['missing', 'pending_verification', 'verified', 'removed', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class RecipientConsent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['recipientConsent']
    state: Literal['missing', 'active', 'suppressed', 'expired', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class TestConversation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['testConversation']
    state: Literal[
        'not_started', 'inbound_only', 'pending', 'verified', 'failed', 'unknown'
    ]
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')


class FeatureReadines(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    area: Literal['featureReadiness']
    state: Literal['ready', 'blocked', 'degraded', 'unavailable', 'unknown']
    subject_ref: SubjectRef | None = Field(..., alias='subjectRef')
    label: str = Field(..., max_length=160, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    explanation: str = Field(..., max_length=500, min_length=1)
    allowed_reads: list[AllowedRead] = Field(..., alias='allowedReads', max_length=40)
    allowed_actions: list[AllowedAction] = Field(
        ..., alias='allowedActions', max_length=40
    )
    next_action: NextAction = Field(..., alias='nextAction')
    retryability: Literal[
        'never',
        'safe_read',
        'after_owner_action',
        'after_provider_update',
        'after_operator_action',
    ]
    last_verified_at: AwareDatetime | None = Field(..., alias='lastVerifiedAt')
    support_receipt: SupportReceipt | None = Field(..., alias='supportReceipt')
    feature_key: str = Field(..., alias='featureKey', max_length=120, min_length=1)


class JourneyState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['assistant-journey-state.v1'] = Field(
        ..., alias='schemaVersion'
    )
    product_availability: ProductAvailability = Field(..., alias='productAvailability')
    operator_activation: OperatorActivation = Field(..., alias='operatorActivation')
    assistant_account: AssistantAccount = Field(..., alias='assistantAccount')
    provider_connections: list[ProviderConnection] = Field(
        ..., alias='providerConnections', max_length=100
    )
    sender_registration: SenderRegistration = Field(..., alias='senderRegistration')
    sender_binding: SenderBinding = Field(..., alias='senderBinding')
    recipient_enrollment: RecipientEnrollment = Field(..., alias='recipientEnrollment')
    recipient_consent: RecipientConsent = Field(..., alias='recipientConsent')
    test_conversation: TestConversation = Field(..., alias='testConversation')
    feature_readiness: list[FeatureReadines] = Field(
        ..., alias='featureReadiness', max_length=100
    )
    evaluated_at: AwareDatetime = Field(..., alias='evaluatedAt')


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    label: str = Field(..., max_length=120, min_length=1)
    href: str = Field(..., max_length=240, min_length=1)


class Check(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Literal[
        'connection',
        'sender',
        'registration',
        'binding',
        'recipient',
        'consent',
        'webhook',
        'worker',
        'schedule_dispatch',
        'delivery_callback',
    ]
    state: Literal['healthy', 'pending', 'needs_attention', 'blocked', 'unknown']
    summary: str = Field(..., max_length=240, min_length=1)
    owner: Literal['operator', 'account_owner', 'provider', 'system']
    last_verified_at: AwareDatetime | None = Field(None, alias='lastVerifiedAt')
    failed_step: str | None = Field(
        None, alias='failedStep', pattern='^[a-z][a-z0-9_.:-]{2,120}$'
    )
    retry_safety: Literal['safe', 'confirmation_required', 'unsafe', 'unknown'] = Field(
        ..., alias='retrySafety'
    )
    action: Action | None = None
    receipt_ref: str | None = Field(
        None,
        alias='receiptRef',
        max_length=160,
        min_length=1,
        pattern='^[a-z][a-z0-9_]*_[A-Za-z0-9_-]{3,128}$',
    )


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    checked_at: AwareDatetime = Field(..., alias='checkedAt')
    journey_state: JourneyState = Field(..., alias='journeyState')
    checks: list[Check] = Field(..., max_length=10, min_length=10)
    support_ref: str = Field(
        ...,
        alias='supportRef',
        max_length=160,
        min_length=1,
        pattern='^[a-z][a-z0-9_]*_[A-Za-z0-9_-]{3,128}$',
    )


class ResultDigest(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str = Field(..., pattern='^[a-z][a-z0-9_]{2,80}$')
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never', 'safe_read', 'same_identity_after_reconciliation', 'new_review'
    ] = Field(..., alias='retryClass')
    trace_ref: str | None = Field(
        None, alias='traceRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class NextAction10(RootModel[str]):
    root: str = Field(..., max_length=240, min_length=1)


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction10] = Field(..., alias='nextActions', max_length=20)


class NextCursor(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._~:-]{1,512}$')


class Offload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantDiagnosticsGetOutput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    data: Data
    receipt: Receipt | None = None
    meta: Meta
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    offload: Offload | None = None
    truncated: bool
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Receipt1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class Meta1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction10] = Field(..., alias='nextActions', max_length=20)


class Offload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantDiagnosticsGetOutput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    receipt: Receipt1 | None = None
    meta: Meta1
    resource_uri: str = Field(..., alias='resourceUri', max_length=240)
    offload: Offload1
    truncated: Literal[True]
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Error2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Literal[
        'not_authenticated',
        'validation_failed',
        'idempotency_key_invalid',
        'request_too_large',
        'not_found',
        'registration_review_expired',
        'schedule_confirmation_conflict',
        'response_too_large',
        'service_not_configured',
        'invalid_caller',
        'invalid_request',
        'policy_denied',
        'approval_required',
        'assistant_service_failed',
        'assistant_request_cancelled',
        'assistant_request_failed',
        'assistant_resource_failed',
        'assistant_response_invalid',
        'assistant_response_rejected',
        'assistant_response_too_large',
        'mcp_http_error',
        'mcp_request_timeout',
        'response_lost',
        'service_unavailable',
        'idempotency_conflict',
        'idempotency_in_progress',
    ]
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never',
        'safe_read',
        'receipt_lookup',
        'reconcile_first',
        'same_identity_after_reconciliation',
        'new_review',
    ] = Field(..., alias='retryClass')
    request_ref: str | None = Field(
        None, alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    next_actions: list[NextAction10] = Field(..., alias='nextActions', max_length=20)


class AssistantDiagnosticsGetOutput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[False]
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    truncated: Literal[False]
    untrusted_content: bool = Field(..., alias='untrustedContent')
    error: Error2


class AssistantDiagnosticsGetOutput(
    RootModel[
        AssistantDiagnosticsGetOutput1
        | AssistantDiagnosticsGetOutput2
        | AssistantDiagnosticsGetOutput3
    ]
):
    root: (
        AssistantDiagnosticsGetOutput1
        | AssistantDiagnosticsGetOutput2
        | AssistantDiagnosticsGetOutput3
    )


class AssistantDiagnosticsGetModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: AssistantDiagnosticsGetInput
    output: AssistantDiagnosticsGetOutput
