# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AudienceDigest(RootModel[str]):
    root: str = Field(
        None,
        description='SHA-256 digest of the reviewed audience, or null when no audience exists.',
        pattern='^[a-f0-9]{64}$',
    )


class SpendLimit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    currency: str = Field(
        ...,
        description='Three-letter currency code for the approved spend ceiling.',
        pattern='^[A-Z]{3}$',
    )
    amount_minor: int = Field(
        ...,
        alias='amountMinor',
        description='Maximum approved spend in integer minor currency units.',
        ge=-9007199254740991,
        le=9007199254740991,
    )


class TypedConfirmation(RootModel[str]):
    root: str = Field(
        None,
        description='Typed confirmation required by the approval policy, or null when policy does not require one.',
        max_length=160,
        min_length=1,
    )


class AssistantApprovalDecideInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    approval_ref: str = Field(
        ...,
        alias='approvalRef',
        description='Opaque pending approval reference being decided.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    command_ref: str = Field(
        ...,
        alias='commandRef',
        description='Opaque command reference bound to the reviewed approval.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    plan_digest: str = Field(
        ...,
        alias='planDigest',
        description='SHA-256 digest of the immutable reviewed plan.',
        pattern='^[a-f0-9]{64}$',
    )
    context_version_ref: str = Field(
        ...,
        alias='contextVersionRef',
        description='Opaque immutable context-version reference used during review.',
        pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$',
    )
    action_digest: str = Field(
        ...,
        alias='actionDigest',
        description='SHA-256 digest of the exact reviewed action.',
        pattern='^[a-f0-9]{64}$',
    )
    argument_digest: str = Field(
        ...,
        alias='argumentDigest',
        description='SHA-256 digest of the exact reviewed action arguments.',
        pattern='^[a-f0-9]{64}$',
    )
    audience_digest: AudienceDigest | None = Field(
        None,
        alias='audienceDigest',
        description='SHA-256 digest of the reviewed audience, or null when no audience exists.',
    )
    spend_limit: SpendLimit | None = Field(
        None,
        alias='spendLimit',
        description='Exact approved spend ceiling, or null when the action has no spend.',
    )
    decision: Literal['approve', 'reject'] = Field(
        ..., description='Owner decision for this exact immutable approval.'
    )
    typed_confirmation: TypedConfirmation | None = Field(
        None,
        alias='typedConfirmation',
        description='Typed confirmation required by the approval policy, or null when policy does not require one.',
    )
    decided_at: AwareDatetime = Field(
        ...,
        alias='decidedAt',
        description='ISO 8601 timestamp when the owner made this decision.',
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        description='Stable retry identity for this exact approval decision.',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )


class CycleRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class GrantRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class AudienceDigest1(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class SpendLimit1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    currency: str = Field(..., pattern='^[A-Z]{3}$')
    amount_minor: int = Field(..., alias='amountMinor', ge=0, le=9007199254740991)


class OccurrenceRef(RootModel[str]):
    root: str = Field(..., pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$')


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    approval_ref: str = Field(
        ..., alias='approvalRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    command_ref: str = Field(
        ..., alias='commandRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    cycle_ref: CycleRef | None = Field(..., alias='cycleRef')
    grant_ref: GrantRef | None = Field(..., alias='grantRef')
    requested_action_digest: str = Field(
        ..., alias='requestedActionDigest', pattern='^[a-f0-9]{64}$'
    )
    approved_argument_digest: str = Field(
        ..., alias='approvedArgumentDigest', pattern='^[a-f0-9]{64}$'
    )
    audience_digest: AudienceDigest1 | None = Field(..., alias='audienceDigest')
    spend_limit: SpendLimit1 | None = Field(..., alias='spendLimit')
    occurrence_ref: OccurrenceRef | None = Field(..., alias='occurrenceRef')
    state: Literal[
        'pending', 'approved', 'rejected', 'expired', 'consumed', 'cancelled'
    ]
    requested_at: AwareDatetime = Field(..., alias='requestedAt')
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    decided_at: AwareDatetime | None = Field(..., alias='decidedAt')
    consumed_at: AwareDatetime | None = Field(..., alias='consumedAt')


class ResultDigest(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str = Field(..., pattern='^[a-z][a-z0-9_]{2,80}$')
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never', 'safe_read', 'same_identity_after_reconciliation', 'new_review'
    ] = Field(..., alias='retryClass')
    trace_ref: str | None = Field(
        None, alias='traceRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class NextAction(RootModel[str]):
    root: str = Field(..., max_length=240, min_length=1)


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class NextCursor(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._~:-]{1,512}$')


class Offload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantApprovalDecideOutput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    data: Data
    receipt: Receipt | None = None
    meta: Meta
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    offload: Offload | None = None
    truncated: bool
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Receipt1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    receipt_ref: str = Field(
        ..., alias='receiptRef', pattern='^[a-z][a-z0-9]{1,31}_[A-Za-z0-9_-]{3,160}$'
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        max_length=240,
        min_length=8,
        pattern='^[A-Za-z0-9][A-Za-z0-9:._/+~-]*$',
    )
    request_digest: str = Field(..., alias='requestDigest', pattern='^[a-f0-9]{64}$')
    result_digest: ResultDigest | None = Field(..., alias='resultDigest')
    state: Literal[
        'accepted',
        'denied',
        'pending_provider',
        'confirmed',
        'failed',
        'unknown',
        'reconciled',
        'cancelled',
    ]
    replayed: bool
    occurred_at: AwareDatetime = Field(..., alias='occurredAt')
    error: Error | None


class Meta1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_ref: str = Field(
        ..., alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    projection_version: str | None = Field(
        None, alias='projectionVersion', max_length=80, min_length=1
    )
    fetched_at: AwareDatetime | None = Field(None, alias='fetchedAt')
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class Offload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_uri: str = Field(..., alias='resourceUri', max_length=240, min_length=1)
    next_cursor: NextCursor | None = Field(..., alias='nextCursor')
    reason: Literal['result_exceeded_inline_budget']


class AssistantApprovalDecideOutput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[True]
    receipt: Receipt1 | None = None
    meta: Meta1
    resource_uri: str = Field(..., alias='resourceUri', max_length=240)
    offload: Offload1
    truncated: Literal[True]
    untrusted_content: bool = Field(..., alias='untrustedContent')


class Error2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Literal[
        'not_authenticated',
        'validation_failed',
        'idempotency_key_invalid',
        'request_too_large',
        'not_found',
        'registration_review_expired',
        'schedule_confirmation_conflict',
        'response_too_large',
        'service_not_configured',
        'invalid_caller',
        'invalid_request',
        'policy_denied',
        'approval_required',
        'assistant_service_failed',
        'assistant_request_cancelled',
        'assistant_request_failed',
        'assistant_resource_failed',
        'assistant_response_invalid',
        'assistant_response_rejected',
        'assistant_response_too_large',
        'mcp_http_error',
        'mcp_request_timeout',
        'response_lost',
        'service_unavailable',
        'idempotency_conflict',
        'idempotency_in_progress',
    ]
    message: str = Field(..., max_length=500, min_length=1)
    retry_class: Literal[
        'never',
        'safe_read',
        'receipt_lookup',
        'reconcile_first',
        'same_identity_after_reconciliation',
        'new_review',
    ] = Field(..., alias='retryClass')
    request_ref: str | None = Field(
        None, alias='requestRef', pattern='^[A-Za-z0-9._:-]{1,160}$'
    )
    next_actions: list[NextAction] = Field(..., alias='nextActions', max_length=20)


class AssistantApprovalDecideOutput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    ok: Literal[False]
    resource_uri: str | None = Field(None, alias='resourceUri', max_length=240)
    truncated: Literal[False]
    untrusted_content: bool = Field(..., alias='untrustedContent')
    error: Error2


class AssistantApprovalDecideOutput(
    RootModel[
        AssistantApprovalDecideOutput1
        | AssistantApprovalDecideOutput2
        | AssistantApprovalDecideOutput3
    ]
):
    root: (
        AssistantApprovalDecideOutput1
        | AssistantApprovalDecideOutput2
        | AssistantApprovalDecideOutput3
    )


class AssistantApprovalDecideModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: AssistantApprovalDecideInput
    output: AssistantApprovalDecideOutput
