# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class HarvestPaaStartInput(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pages: int | None = Field(
        1,
        description='Organic result pages to capture. Default 1, maximum 2. Page 2 is captured when available before harvesting PAA on the original first page; it does not add a second PAA graph. Pagination output reports the pages actually captured.',
        ge=1,
        le=2,
    )
    query: str = Field(
        ...,
        description='The search topic, exactly as it should be searched, e.g. "best hvac company in Denver". Include the place here when you want it in the search terms — the server sends your query to Google unchanged and never adds or removes a location.',
        min_length=1,
    )
    location: str | None = Field(
        None,
        description='Where Google should think the searcher is, e.g. "Denver, CO". Sets the Google UULE parameter only — it never changes your query text and never selects a proxy. To put the place in the search terms too, write it into query.',
    )
    max_questions: int | None = Field(
        30,
        alias='maxQuestions',
        description='PAA questions to extract. Default 30, maximum 200. Use 10 for quick probes, 100-200 for deep research. Billed per extracted question; unused hold refunded.',
        ge=1,
        le=200,
    )
    gl: str | None = Field(
        'us',
        description='Google country code inferred from location or user language.',
        max_length=2,
        min_length=2,
    )
    hl: str | None = Field(
        'en',
        description='Google interface/content language inferred from the user request.',
    )
    device: Literal['desktop', 'mobile'] | None = Field(
        'desktop',
        description='SERP device context. Use mobile only for mobile rankings.',
    )
    idempotency_key: str = Field(
        ...,
        alias='idempotencyKey',
        description='Required durable recovery identity for this logical harvest. Reuse this exact key only after an uncertain/lost response or while recovering the same job; never replace it merely because polling timed out.',
        max_length=200,
        min_length=8,
    )
    serp_identity: str | None = Field(
        None,
        alias='serpIdentity',
        description='Optional persistent SERP identity created with serp_identity_create. Reuses the same saved browser state and fixed network address across calls.',
        pattern='^[a-z0-9][a-z0-9_-]{0,63}$',
    )
    include_all_serp_features: bool | None = Field(
        False,
        alias='includeAllSerpFeatures',
        description='Capture every optional same-page SERP surface: local pack, forums, videos, AI Overview/AI Mode, and What People Are Saying.',
    )
    include_local_pack: bool | None = Field(
        False,
        alias='includeLocalPack',
        description='Include Google local/map-pack businesses and merge their entity IDs.',
    )
    include_forums: bool | None = Field(
        False,
        alias='includeForums',
        description='Include Discussions and Forums results.',
    )
    include_videos: bool | None = Field(
        False,
        alias='includeVideos',
        description='Include video result names and URLs present on the original SERP.',
    )
    include_ai_overview: bool | None = Field(
        False,
        alias='includeAiOverview',
        description='Include AI Overview and AI Mode text and citations when present.',
    )
    include_what_people_saying: bool | None = Field(
        False,
        alias='includeWhatPeopleSaying',
        description='Include the What People Are Saying social surface when present.',
    )


class Status(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    state: Literal['pending', 'running']
    terminal: Literal[False]
    poll_after_seconds: int = Field(
        ..., alias='pollAfterSeconds', ge=1, le=9007199254740991
    )
    retry_guidance: str = Field(..., alias='retryGuidance')


class HarvestPaaStartOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    job_id: str = Field(..., alias='jobId')
    operation_id: str = Field(..., alias='operationId')
    task_id: str = Field(..., alias='taskId')
    status: Status
    replayed: bool
    status_tool: Literal['harvest_paa_status'] = Field(..., alias='statusTool')


class HarvestPaaStartModels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input: HarvestPaaStartInput
    output: HarvestPaaStartOutput
